//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendamentosEnviosVariaveisTemplates
    {
        public int id { get; set; }
        public int agendamentoid { get; set; }
        public int templatevariavelid { get; set; }
        public string texto { get; set; }
        public string nomevarialvelchatbot { get; set; }
    
        public virtual AgendamentosEnviosTemplates AgendamentosEnviosTemplates { get; set; }
        public virtual TemplatesMetaVariaveis TemplatesMetaVariaveis { get; set; }
    }
}
