//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArvoreDiagnosticosPerguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArvoreDiagnosticosPerguntas()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
        }
    
        public int id { get; set; }
        public int arvoreid { get; set; }
        public int ordem { get; set; }
        public string tipo { get; set; }
        public string pergunta { get; set; }
        public string simpotencialproblema { get; set; }
        public string simcomoresolver { get; set; }
        public string simcomoresolverdetalhado { get; set; }
        public string simsugestaopecasreparo { get; set; }
        public string naopotencialproblema { get; set; }
        public string naocomoresolver { get; set; }
        public string naocomoresolverdetalhado { get; set; }
        public string naosugestaopecasreparo { get; set; }
        public string consideracoesfinais { get; set; }
        public string ativo { get; set; }
    
        public virtual ArvoreDiagnosticos ArvoreDiagnosticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
    }
}
