//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArvoreDiagnosticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArvoreDiagnosticos()
        {
            this.ArvoreDiagnosticosFamilias = new HashSet<ArvoreDiagnosticosFamilias>();
            this.ArvoreDiagnosticosPerguntas = new HashSet<ArvoreDiagnosticosPerguntas>();
            this.ArvoreDiagnosticosProdutos = new HashSet<ArvoreDiagnosticosProdutos>();
        }
    
        public int id { get; set; }
        public string reclamacao { get; set; }
        public string ativo { get; set; }
        public string privacidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArvoreDiagnosticosFamilias> ArvoreDiagnosticosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArvoreDiagnosticosPerguntas> ArvoreDiagnosticosPerguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArvoreDiagnosticosProdutos> ArvoreDiagnosticosProdutos { get; set; }
    }
}
