//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendimentosDefeitosReclamados
    {
        public int id { get; set; }
        public int atendimentoid { get; set; }
        public Nullable<int> atendimentoprodutoid { get; set; }
        public string defeitoreclamado { get; set; }
        public Nullable<int> defeitoreclamadoid { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual AtendimentosProdutos AtendimentosProdutos { get; set; }
        public virtual DefeitosReclamados DefeitosReclamados { get; set; }
    }
}
