//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendimentosInteracoesAnexos
    {
        public int id { get; set; }
        public int atendimentointeracaoid { get; set; }
        public int fileid { get; set; }
    
        public virtual AtendimentosInteracoes AtendimentosInteracoes { get; set; }
        public virtual Files Files { get; set; }
    }
}
