//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendimentosProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtendimentosProdutos()
        {
            this.AtendimentosDefeitosReclamados = new HashSet<AtendimentosDefeitosReclamados>();
        }
    
        public int id { get; set; }
        public int atendimentoid { get; set; }
        public int produtoid { get; set; }
        public int quantidade { get; set; }
        public decimal valorunitario { get; set; }
        public decimal valortotal { get; set; }
        public string lote { get; set; }
        public string defeitoreclamado { get; set; }
        public Nullable<int> defeitoreclamadoid { get; set; }
        public string obs { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosDefeitosReclamados> AtendimentosDefeitosReclamados { get; set; }
        public virtual DefeitosReclamados DefeitosReclamados { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
