//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendimentosEntidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtendimentosEntidades()
        {
            this.AtendimentosEntidadesContatos = new HashSet<AtendimentosEntidadesContatos>();
        }
    
        public int id { get; set; }
        public int atendimentoid { get; set; }
        public int entidadeid { get; set; }
        public string entidadedeslocamento { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual Entidades Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosEntidadesContatos> AtendimentosEntidadesContatos { get; set; }
    }
}
