//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendimentosChats
    {
        public int id { get; set; }
        public int atendimentoid { get; set; }
        public int chatid { get; set; }
        public Nullable<int> usuarioidmesclagem { get; set; }
        public string usuarionomemesclagem { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual Chats Chats { get; set; }
    }
}
