//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendimentos()
        {
            this.AtendimentosAnexos = new HashSet<AtendimentosAnexos>();
            this.AtendimentosAtendimentos = new HashSet<AtendimentosAtendimentos>();
            this.AtendimentosAtendimentos1 = new HashSet<AtendimentosAtendimentos>();
            this.CamposPersonalizadosAtendimentos = new HashSet<CamposPersonalizadosAtendimentos>();
            this.AtendimentosChats = new HashSet<AtendimentosChats>();
            this.AtendimentosDadosMarketplaces = new HashSet<AtendimentosDadosMarketplaces>();
            this.AtendimentosDefeitosReclamados = new HashSet<AtendimentosDefeitosReclamados>();
            this.AtendimentosEntidades = new HashSet<AtendimentosEntidades>();
            this.AtendimentosOrdensServicos = new HashSet<AtendimentosOrdensServicos>();
            this.AtendimentosProdutos = new HashSet<AtendimentosProdutos>();
            this.AtendimentosSeguidores = new HashSet<AtendimentosSeguidores>();
            this.AtendimentosTags = new HashSet<AtendimentosTags>();
            this.AtendimentosInteracoes = new HashSet<AtendimentosInteracoes>();
            this.Atividades = new HashSet<Atividades>();
            this.AvaliacoesAtendimentos = new HashSet<AvaliacoesAtendimentos>();
            this.CampanhasContatos = new HashSet<CampanhasContatos>();
            this.Chats = new HashSet<Chats>();
            this.EnderecoProduto = new HashSet<EnderecoProduto>();
            this.IASConsumoTokens = new HashSet<IASConsumoTokens>();
            this.NaoConformidadesAtendimentos = new HashSet<NaoConformidadesAtendimentos>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.Pedidos = new HashSet<Pedidos>();
            this.VisualizacaoConsultaPublicaLinks = new HashSet<VisualizacaoConsultaPublicaLinks>();
        }
    
        public int id { get; set; }
        public int numeroprotocolo { get; set; }
        public string origemcontato { get; set; }
        public string tipoatendimento { get; set; }
        public System.DateTime dataabertura { get; set; }
        public Nullable<System.DateTime> datafechamento { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public string tipoconsumidor { get; set; }
        public string melhorhorarioparacontato { get; set; }
        public Nullable<int> produtoid { get; set; }
        public string lote { get; set; }
        public string notafiscal { get; set; }
        public string notaremessa { get; set; }
        public string notaretorno { get; set; }
        public Nullable<System.DateTime> datacompra { get; set; }
        public Nullable<int> notafiscalfileid { get; set; }
        public Nullable<int> fotoproduto1fileid { get; set; }
        public Nullable<int> fotoproduto2fileid { get; set; }
        public Nullable<int> fotoproduto3fileid { get; set; }
        public Nullable<int> fotoproduto4fileid { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public Nullable<int> defeitoconstatadoid { get; set; }
        public string tipoocorrencia { get; set; }
        public string assunto { get; set; }
        public string descricao { get; set; }
        public string situacao { get; set; }
        public string status { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public Nullable<int> usuarioidabertura { get; set; }
        public string usuarionomeabertura { get; set; }
        public Nullable<int> grupocallcenterid { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public Nullable<int> defeitoreclamadoid { get; set; }
        public Nullable<int> arvoreperguntaid { get; set; }
        public string potencialproblema { get; set; }
        public string dispositivoabertura { get; set; }
        public string lidoconsumidor { get; set; }
        public Nullable<int> fileid1 { get; set; }
        public Nullable<int> contatoid { get; set; }
        public string descricaohtml { get; set; }
        public string cc { get; set; }
        public string cco { get; set; }
        public Nullable<int> postoid { get; set; }
        public Nullable<int> statusatendimentoid { get; set; }
        public Nullable<int> tipoatendimentoid { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<System.DateTime> date5 { get; set; }
        public Nullable<System.DateTime> date6 { get; set; }
        public Nullable<int> fotoproduto5fileid { get; set; }
        public Nullable<int> fotoproduto6fileid { get; set; }
        public Nullable<int> fotoproduto7fileid { get; set; }
        public Nullable<int> fotoproduto8fileid { get; set; }
        public string para { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public Nullable<System.DateTime> dataagendamento { get; set; }
        public Nullable<int> transportadoraid { get; set; }
        public string defeitoreclamado { get; set; }
        public string char1 { get; set; }
        public Nullable<int> integracaomarketplaceid { get; set; }
        public Nullable<System.DateTime> dataultimaatualizacao { get; set; }
        public string messageid { get; set; }
        public Nullable<int> seg_apoliceid { get; set; }
        public Nullable<int> seg_coberturaid { get; set; }
        public Nullable<int> seg_itemprodutoid { get; set; }
        public Nullable<int> apoliceid { get; set; }
        public Nullable<decimal> distanciacalculada { get; set; }
    
        public virtual ArvoreDiagnosticosPerguntas ArvoreDiagnosticosPerguntas { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual DefeitosConstatados DefeitosConstatados { get; set; }
        public virtual DefeitosReclamados DefeitosReclamados { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual Files Files2 { get; set; }
        public virtual Files Files3 { get; set; }
        public virtual Files Files4 { get; set; }
        public virtual Files Files5 { get; set; }
        public virtual Files Files6 { get; set; }
        public virtual Files Files7 { get; set; }
        public virtual Files Files8 { get; set; }
        public virtual Files Files9 { get; set; }
        public virtual GruposCallCenter GruposCallCenter { get; set; }
        public virtual IntegracoesMarketplaces IntegracoesMarketplaces { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        public virtual Seg_Apolices Seg_Apolices { get; set; }
        public virtual Seg_Coberturas Seg_Coberturas { get; set; }
        public virtual Seg_ItensProdutos Seg_ItensProdutos { get; set; }
        public virtual StatusAtendimentos StatusAtendimentos { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        public virtual TiposAtendimentos TiposAtendimentos { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosAnexos> AtendimentosAnexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosAtendimentos> AtendimentosAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosAtendimentos> AtendimentosAtendimentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosAtendimentos> CamposPersonalizadosAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosChats> AtendimentosChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosDadosMarketplaces> AtendimentosDadosMarketplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosDefeitosReclamados> AtendimentosDefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosEntidades> AtendimentosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosOrdensServicos> AtendimentosOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosProdutos> AtendimentosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosSeguidores> AtendimentosSeguidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosTags> AtendimentosTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosInteracoes> AtendimentosInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividades> Atividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacoesAtendimentos> AvaliacoesAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampanhasContatos> CampanhasContatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnderecoProduto> EnderecoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IASConsumoTokens> IASConsumoTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesAtendimentos> NaoConformidadesAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualizacaoConsultaPublicaLinks> VisualizacaoConsultaPublicaLinks { get; set; }
    }
}
