//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividades
    {
        public int id { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public System.DateTime datacriacao { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> datafim { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string obs { get; set; }
        public int usuarioidabertura { get; set; }
        public string usuarionomeabertura { get; set; }
        public int usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public Nullable<int> prioridade { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dataconclusao { get; set; }
        public Nullable<int> finalidadeid { get; set; }
        public string agendamentoordemservico { get; set; }
        public Nullable<int> chatid { get; set; }
        public string ideventogoogleagenda { get; set; }
        public Nullable<int> contatoid { get; set; }
        public Nullable<int> entidadeid { get; set; }
        public Nullable<int> oportunidadeid { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual Chats Chats { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual FinalidadesAtividades FinalidadesAtividades { get; set; }
        public virtual Oportunidades Oportunidades { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
