//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automacoes()
        {
            this.AutomacoesAcoes = new HashSet<AutomacoesAcoes>();
            this.AutomacoesCondicoes = new HashSet<AutomacoesCondicoes>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string codigo { get; set; }
        public string modulo { get; set; }
        public string campo { get; set; }
        public string valorde { get; set; }
        public string valorpara { get; set; }
        public string ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomacoesAcoes> AutomacoesAcoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomacoesCondicoes> AutomacoesCondicoes { get; set; }
    }
}
