//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomacoesAcoes
    {
        public int id { get; set; }
        public int automacaoid { get; set; }
        public string codigo { get; set; }
        public string acao { get; set; }
        public string parametros { get; set; }
    
        public virtual Automacoes Automacoes { get; set; }
    }
}
