//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacoesAtendimentos
    {
        public int id { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public Nullable<int> chatid { get; set; }
        public System.DateTime datageracao { get; set; }
        public Nullable<int> nota { get; set; }
        public string imagem { get; set; }
        public string comentarios { get; set; }
        public string pergunta1 { get; set; }
        public string resposta1 { get; set; }
        public string pergunta2 { get; set; }
        public string resposta2 { get; set; }
        public string pergunta3 { get; set; }
        public string resposta3 { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> dataresposta { get; set; }
        public string legendanota { get; set; }
        public string texto { get; set; }
        public Nullable<int> contatoid { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual Chats Chats { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
