//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamposPersonalizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CamposPersonalizados()
        {
            this.CamposPersonalizadosAtendimentos = new HashSet<CamposPersonalizadosAtendimentos>();
            this.CamposPersonalizadosCondicoes = new HashSet<CamposPersonalizadosCondicoes>();
            this.CamposPersonalizadosContatos = new HashSet<CamposPersonalizadosContatos>();
            this.CamposPersonalizadosEntidades = new HashSet<CamposPersonalizadosEntidades>();
            this.CamposPersonalizadosItems = new HashSet<CamposPersonalizadosItems>();
            this.CamposPersonalizadosOrdensServicosProdutos = new HashSet<CamposPersonalizadosOrdensServicosProdutos>();
            this.CamposPersonalizadosPedidos = new HashSet<CamposPersonalizadosPedidos>();
            this.ContatosLayoutImportacao = new HashSet<ContatosLayoutImportacao>();
            this.CamposPersonalizadosOrdensServicos = new HashSet<CamposPersonalizadosOrdensServicos>();
        }
    
        public int id { get; set; }
        public string tabela { get; set; }
        public string nomecampo { get; set; }
        public string tipocampo { get; set; }
        public string obrigatorio { get; set; }
        public string ativo { get; set; }
        public Nullable<int> ordem { get; set; }
        public string valorpadrao { get; set; }
        public string nomeiniciogrupo { get; set; }
        public Nullable<int> maximocaracteres { get; set; }
        public string disponivelsomentefabricante { get; set; }
        public string obrigatorioparafinalizar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosAtendimentos> CamposPersonalizadosAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosCondicoes> CamposPersonalizadosCondicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosContatos> CamposPersonalizadosContatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosEntidades> CamposPersonalizadosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosItems> CamposPersonalizadosItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosOrdensServicosProdutos> CamposPersonalizadosOrdensServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosPedidos> CamposPersonalizadosPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContatosLayoutImportacao> ContatosLayoutImportacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosOrdensServicos> CamposPersonalizadosOrdensServicos { get; set; }
    }
}
