//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campanhas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campanhas()
        {
            this.CampanhasContatos = new HashSet<CampanhasContatos>();
            this.Chats = new HashSet<Chats>();
        }
    
        public int id { get; set; }
        public System.DateTime datacriacao { get; set; }
        public int usuarioidcriacao { get; set; }
        public string usuarionomecriacao { get; set; }
        public string tipo { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public int numeroid { get; set; }
        public int templateid { get; set; }
        public int diaspositivacao { get; set; }
        public System.DateTime datadisparo { get; set; }
        public string status { get; set; }
        public string execucaolocal { get; set; }
    
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
        public virtual TemplatesMeta TemplatesMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampanhasContatos> CampanhasContatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
    }
}
