//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampanhasContatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampanhasContatos()
        {
            this.AgendamentosEnviosTemplates = new HashSet<AgendamentosEnviosTemplates>();
        }
    
        public int id { get; set; }
        public int campanhaid { get; set; }
        public int contatoid { get; set; }
        public Nullable<System.DateTime> dataenvio { get; set; }
        public string status { get; set; }
        public string positivado { get; set; }
        public string mensagemerro { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public Nullable<int> oportunidadeid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentosEnviosTemplates> AgendamentosEnviosTemplates { get; set; }
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual Campanhas Campanhas { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual Oportunidades Oportunidades { get; set; }
    }
}
