//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrinhoConversas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrinhoConversas()
        {
            this.CarrinhoConversasVariacoes = new HashSet<CarrinhoConversasVariacoes>();
        }
    
        public int id { get; set; }
        public System.DateTime datacriacao { get; set; }
        public int contatoid { get; set; }
        public string sku { get; set; }
        public string nomeproduto { get; set; }
        public int quantidade { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string idcarrinhoplataforma { get; set; }
        public string linkproduto { get; set; }
    
        public virtual Contatos Contatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrinhoConversasVariacoes> CarrinhoConversasVariacoes { get; set; }
    }
}
