//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int id { get; set; }
        public int postoid { get; set; }
        public int pecaid { get; set; }
        public decimal quantidade { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<decimal> percentualicms { get; set; }
        public Nullable<decimal> valoricms { get; set; }
        public Nullable<decimal> percentualipi { get; set; }
        public Nullable<decimal> valoripi { get; set; }
        public decimal valortotal { get; set; }
        public int tabelaprecovendaid { get; set; }
        public string char1 { get; set; }
        public Nullable<decimal> percentualpis { get; set; }
        public Nullable<decimal> valorpis { get; set; }
        public Nullable<decimal> percentualcofins { get; set; }
        public Nullable<decimal> valorcofins { get; set; }
        public Nullable<decimal> precotabela { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public string obs { get; set; }
        public string char2 { get; set; }
        public Nullable<decimal> dec1 { get; set; }
    
        public virtual Pecas Pecas { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual TabelasPrecos TabelasPrecos { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
