//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosProdutos()
        {
            this.CatalogosProdutosEstruturasVersionadasReferencias = new HashSet<CatalogosProdutosEstruturasVersionadasReferencias>();
        }
    
        public int id { get; set; }
        public int catalogoid { get; set; }
        public int produtoid { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        public virtual Produtos Produtos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosProdutosEstruturasVersionadasReferencias> CatalogosProdutosEstruturasVersionadasReferencias { get; set; }
    }
}
