//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosSistemas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosSistemas()
        {
            this.CatalogosConjuntos = new HashSet<CatalogosConjuntos>();
        }
    
        public int id { get; set; }
        public int catalogoid { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<int> capafileid { get; set; }
        public int ordem { get; set; }
        public string ativo { get; set; }
        public string svg { get; set; }
        public string hash { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosConjuntos> CatalogosConjuntos { get; set; }
        public virtual Files Files { get; set; }
    }
}
