//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosConjuntos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosConjuntos()
        {
            this.CatalogosConjuntosPecas = new HashSet<CatalogosConjuntosPecas>();
        }
    
        public int id { get; set; }
        public int catalogosistemaid { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<int> capafileid { get; set; }
        public string svg { get; set; }
        public int ordem { get; set; }
        public string ativo { get; set; }
        public string hash { get; set; }
        public Nullable<int> svgfileid { get; set; }
    
        public virtual CatalogosSistemas CatalogosSistemas { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosConjuntosPecas> CatalogosConjuntosPecas { get; set; }
    }
}
