//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogos()
        {
            this.CatalogosArquivos = new HashSet<CatalogosArquivos>();
            this.CatalogosProdutos = new HashSet<CatalogosProdutos>();
            this.CatalogosSistemas = new HashSet<CatalogosSistemas>();
        }
    
        public int id { get; set; }
        public string hash { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string idioma { get; set; }
        public string versao { get; set; }
        public Nullable<int> capafileid { get; set; }
        public System.DateTime datacriacao { get; set; }
        public string publico { get; set; }
        public int acessos { get; set; }
        public string customcss { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public Nullable<System.DateTime> dataultimaalteracao { get; set; }
        public Nullable<int> usuarioidultimaalteracao { get; set; }
        public string usuarionomeultimaalteracao { get; set; }
        public string svg { get; set; }
        public string destaquelojavirtual { get; set; }
    
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosArquivos> CatalogosArquivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosProdutos> CatalogosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosSistemas> CatalogosSistemas { get; set; }
    }
}
