//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosArquivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogosArquivos()
        {
            this.CatalogosArquivos1 = new HashSet<CatalogosArquivos>();
        }
    
        public int id { get; set; }
        public int catalogoid { get; set; }
        public int fileid { get; set; }
        public string enviadoupload { get; set; }
        public Nullable<int> catalogoarquivopaiid { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosArquivos> CatalogosArquivos1 { get; set; }
        public virtual CatalogosArquivos CatalogosArquivos2 { get; set; }
        public virtual Files Files { get; set; }
    }
}
