//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogosConjuntosPecas
    {
        public int id { get; set; }
        public int catalogoconjuntoid { get; set; }
        public int ordem { get; set; }
        public string item { get; set; }
        public int pecaid { get; set; }
        public string descricao { get; set; }
        public int quantidade { get; set; }
        public string nota { get; set; }
        public string especificacoestecnicas { get; set; }
        public string ativo { get; set; }
    
        public virtual CatalogosConjuntos CatalogosConjuntos { get; set; }
        public virtual Pecas Pecas { get; set; }
    }
}
