//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamadas
    {
        public int id { get; set; }
        public int numeroid { get; set; }
        public Nullable<int> usuarioid { get; set; }
        public string usuarionome { get; set; }
        public string caller { get; set; }
        public string state { get; set; }
        public string callid { get; set; }
        public string linkaudio { get; set; }
        public Nullable<int> talkingdurationseconds { get; set; }
        public Nullable<int> totaldurationseconds { get; set; }
    
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
    }
}
