//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chats()
        {
            this.AgendamentosEnviosTemplates = new HashSet<AgendamentosEnviosTemplates>();
            this.AtendimentosChats = new HashSet<AtendimentosChats>();
            this.Atividades = new HashSet<Atividades>();
            this.AvaliacoesAtendimentos = new HashSet<AvaliacoesAtendimentos>();
            this.ChatsTags = new HashSet<ChatsTags>();
            this.ChatsFallbacks = new HashSet<ChatsFallbacks>();
            this.ChatsMensagens = new HashSet<ChatsMensagens>();
            this.ChatsMensagensAssistente = new HashSet<ChatsMensagensAssistente>();
            this.ChatsMensagensNaoLidas = new HashSet<ChatsMensagensNaoLidas>();
            this.ChatsTranferencias = new HashSet<ChatsTranferencias>();
            this.ChatsVariaveis = new HashSet<ChatsVariaveis>();
        }
    
        public int id { get; set; }
        public System.DateTime datainicio { get; set; }
        public Nullable<System.DateTime> dataencerramento { get; set; }
        public string identificador { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string ConnectionId { get; set; }
        public Nullable<int> grupocallcenterid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string status { get; set; }
        public string origem { get; set; }
        public string valoridentificador { get; set; }
        public Nullable<int> numeroid { get; set; }
        public Nullable<int> contatoid { get; set; }
        public Nullable<int> postoid { get; set; }
        public Nullable<int> usuarioidmesclagem { get; set; }
        public string usuarionomemesclagem { get; set; }
        public Nullable<int> grupocallcenterpaiid { get; set; }
        public Nullable<int> produtoid { get; set; }
        public string botaguardandoacaocontato { get; set; }
        public Nullable<int> chatbotintencaoid { get; set; }
        public string variaveltemporaria { get; set; }
        public Nullable<int> oportunidadeid { get; set; }
        public string nomegrupo { get; set; }
        public Nullable<int> usuarioidencerramento { get; set; }
        public string usuarionomeencerramento { get; set; }
        public string papelDeinicio { get; set; }
        public Nullable<int> fluxoatendimentoetapaid { get; set; }
        public string manterativo { get; set; }
        public Nullable<int> campanhaid { get; set; }
        public string chatreferencia { get; set; }
        public string assistenteid { get; set; }
        public string threadid { get; set; }
        public string ad_ctwa_clid { get; set; }
        public string ad_headline { get; set; }
        public string ad_image_url { get; set; }
        public string ad_media_type { get; set; }
        public string ad_source_id { get; set; }
        public string ad_source_type { get; set; }
        public string ad_source_url { get; set; }
        public string ad_welcome_message { get; set; }
        public string fixada { get; set; }
        public string emespera { get; set; }
        public string privada { get; set; }
        public string hash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentosEnviosTemplates> AgendamentosEnviosTemplates { get; set; }
        public virtual Atendimentos Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosChats> AtendimentosChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividades> Atividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacoesAtendimentos> AvaliacoesAtendimentos { get; set; }
        public virtual Campanhas Campanhas { get; set; }
        public virtual ChatbotsIntencoes ChatbotsIntencoes { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual FluxosAtendimentoMessagingCenterEtapas FluxosAtendimentoMessagingCenterEtapas { get; set; }
        public virtual GruposCallCenter GruposCallCenter { get; set; }
        public virtual GruposCallCenter GruposCallCenter1 { get; set; }
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
        public virtual Oportunidades Oportunidades { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsTags> ChatsTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsFallbacks> ChatsFallbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensagens> ChatsMensagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensagensAssistente> ChatsMensagensAssistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensagensNaoLidas> ChatsMensagensNaoLidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsTranferencias> ChatsTranferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsVariaveis> ChatsVariaveis { get; set; }
    }
}
