//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatsVariaveis
    {
        public int id { get; set; }
        public int chatid { get; set; }
        public string nomevariavel { get; set; }
        public string valor { get; set; }
        public Nullable<System.DateTime> valordate { get; set; }
        public Nullable<decimal> valornumber { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
