//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chatbots
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chatbots()
        {
            this.ChatbotsIntencoes = new HashSet<ChatbotsIntencoes>();
            this.Chatbots1 = new HashSet<Chatbots>();
            this.NumerosWhatsApp = new HashSet<NumerosWhatsApp>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string drawflowjsondata { get; set; }
        public Nullable<int> chatbotedicaoid { get; set; }
        public string ativo { get; set; }
        public Nullable<int> usuarioidedicao { get; set; }
        public string usuarionomeedicao { get; set; }
        public string habilitarpalavrachave { get; set; }
        public string palavrachave { get; set; }
        public string nomeintencaopalavrachave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsIntencoes> ChatbotsIntencoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chatbots> Chatbots1 { get; set; }
        public virtual Chatbots Chatbots2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumerosWhatsApp> NumerosWhatsApp { get; set; }
    }
}
