//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatbotsIntencoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatbotsIntencoes()
        {
            this.ChatbotsCondicoes = new HashSet<ChatbotsCondicoes>();
            this.ChatbotsIntencoesFrases = new HashSet<ChatbotsIntencoesFrases>();
            this.ChatbotsIntencoesOpcoes = new HashSet<ChatbotsIntencoesOpcoes>();
            this.ChatbotsIntencoesOpcoes1 = new HashSet<ChatbotsIntencoesOpcoes>();
            this.ChatbotsVariaveisSeletores = new HashSet<ChatbotsVariaveisSeletores>();
            this.Chats = new HashSet<Chats>();
        }
    
        public int id { get; set; }
        public int chatbotid { get; set; }
        public string tipointencao { get; set; }
        public string descricao { get; set; }
        public string resposta { get; set; }
        public string complementoresposta1 { get; set; }
        public string complementoresposta2 { get; set; }
        public string intencaoencerramentoconversa { get; set; }
        public string permitesolicitaroperador { get; set; }
        public string enviarparafila { get; set; }
        public Nullable<int> grupocallcenteridenviarparafila { get; set; }
        public Nullable<int> chatbotintencaoedicaoid { get; set; }
        public string complementoresposta3 { get; set; }
        public string complementoresposta4 { get; set; }
        public string complementoresposta5 { get; set; }
        public string complementoresposta6 { get; set; }
        public string complementoresposta7 { get; set; }
        public string complementoresposta8 { get; set; }
        public string complementoresposta9 { get; set; }
        public string opcoes { get; set; }
        public string habilitarfallback { get; set; }
        public string aguardarresposta { get; set; }
        public string tiporespostaesperada { get; set; }
        public string habilitarbotoes { get; set; }
        public string intencaodeinicio { get; set; }
        public string acao { get; set; }
        public string idsatribuicao { get; set; }
        public string codigocsharp { get; set; }
        public string exemploretornojson { get; set; }
        public Nullable<int> usuarioidenviarparafila { get; set; }
        public string usuarionomeenviarparafila { get; set; }
        public string subacao { get; set; }
        public string valoratribuicao { get; set; }
        public string char1 { get; set; }
        public string agendarenvio { get; set; }
        public string databaseagendamento { get; set; }
        public string unidadetempoadicionaragendamento { get; set; }
        public Nullable<int> quantidadetempoadicionaragendamento { get; set; }
        public Nullable<int> templateidagendamento { get; set; }
        public Nullable<int> hits { get; set; }
        public string complementovaloratribuicao { get; set; }
        public Nullable<int> idversaoanterior { get; set; }
    
        public virtual Chatbots Chatbots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsCondicoes> ChatbotsCondicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsIntencoesFrases> ChatbotsIntencoesFrases { get; set; }
        public virtual TemplatesMeta TemplatesMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsIntencoesOpcoes> ChatbotsIntencoesOpcoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsIntencoesOpcoes> ChatbotsIntencoesOpcoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsVariaveisSeletores> ChatbotsVariaveisSeletores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
    }
}
