//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatGPT()
        {
            this.ChatGPTDados = new HashSet<ChatGPTDados>();
            this.IASConsumoTokens = new HashSet<IASConsumoTokens>();
            this.WebScraper = new HashSet<WebScraper>();
        }
    
        public int id { get; set; }
        public string chaveapi { get; set; }
        public string prompt { get; set; }
        public int iaid { get; set; }
        public string assistenteid { get; set; }
        public string nome { get; set; }
        public string vectorid { get; set; }
        public string vectorstore { get; set; }
        public string ativo { get; set; }
        public string disponivelmoduloconversas { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<decimal> topt { get; set; }
        public string maxtokens { get; set; }
        public string padraoresumoconversas { get; set; }
    
        public virtual IAS IAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatGPTDados> ChatGPTDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IASConsumoTokens> IASConsumoTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebScraper> WebScraper { get; set; }
    }
}
