//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatsMensagens
    {
        public int id { get; set; }
        public int chatid { get; set; }
        public System.DateTime datahora { get; set; }
        public string de { get; set; }
        public string papelDe { get; set; }
        public string ConnectionId { get; set; }
        public string para { get; set; }
        public string mensagem { get; set; }
        public Nullable<int> fileid { get; set; }
        public string tipomensagem { get; set; }
        public string fileurl { get; set; }
        public string messageid { get; set; }
        public Nullable<int> ack { get; set; }
        public string referencemessageid { get; set; }
        public string encaminhada { get; set; }
        public string deletada { get; set; }
        public Nullable<int> usuarioidde { get; set; }
        public Nullable<int> segundostranscritos { get; set; }
        public string mensageminterna { get; set; }
        public Nullable<System.DateTime> datahoraagendamento { get; set; }
        public string mensagemerroenvio { get; set; }
        public Nullable<int> templateid { get; set; }
        public string templatecategory { get; set; }
        public Nullable<decimal> templatevalormeta { get; set; }
        public Nullable<decimal> templatevaloratweb { get; set; }
        public Nullable<int> agendamentoid { get; set; }
        public string nomeassistenteia { get; set; }
    
        public virtual AgendamentosEnviosTemplates AgendamentosEnviosTemplates { get; set; }
        public virtual Chats Chats { get; set; }
        public virtual Files Files { get; set; }
        public virtual TemplatesMeta TemplatesMeta { get; set; }
    }
}
