//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGPTDados
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
        public string conteudo { get; set; }
        public byte[] embedding { get; set; }
        public int chatgptid { get; set; }
        public string tipotreinamentourl { get; set; }
        public string processado { get; set; }
        public string arquivoid { get; set; }
        public Nullable<int> documentoid { get; set; }
    
        public virtual ChatGPT ChatGPT { get; set; }
        public virtual Documentos Documentos { get; set; }
    }
}
