//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatsTranferencias
    {
        public int id { get; set; }
        public int chatid { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> usuarioidorigem { get; set; }
        public string usuarionomeorigem { get; set; }
        public Nullable<int> usuarioiddestino { get; set; }
        public string usuarionomedestino { get; set; }
        public string statusorigem { get; set; }
        public Nullable<int> grupocallcenteriddestino { get; set; }
        public string statusdestino { get; set; }
        public string mensagem { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual GruposCallCenter GruposCallCenter { get; set; }
    }
}
