//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatbotsIntencoesOpcoes
    {
        public int id { get; set; }
        public int chatbotintencaoid { get; set; }
        public int numero { get; set; }
        public string opcao { get; set; }
        public Nullable<int> chatbotintencaodestinoid { get; set; }
    
        public virtual ChatbotsIntencoes ChatbotsIntencoes { get; set; }
        public virtual ChatbotsIntencoes ChatbotsIntencoes1 { get; set; }
    }
}
