//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatsPausas
    {
        public int id { get; set; }
        public Nullable<int> motivopausaid { get; set; }
        public string status { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public System.DateTime datahorainicio { get; set; }
        public Nullable<System.DateTime> datahorafim { get; set; }
    
        public virtual ChatsMotivosPausas ChatsMotivosPausas { get; set; }
    }
}
