//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatsTokens
    {
        public int id { get; set; }
        public string origem { get; set; }
        public System.DateTime data { get; set; }
        public string token { get; set; }
        public string whatsappid { get; set; }
    }
}
