//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checklists()
        {
            this.ChecklistsFamiliasProdutos = new HashSet<ChecklistsFamiliasProdutos>();
            this.ChecklistsGrupos = new HashSet<ChecklistsGrupos>();
            this.ChecklistsProdutos = new HashSet<ChecklistsProdutos>();
            this.OrdensServicosChecklists = new HashSet<OrdensServicosChecklists>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<int> finalidadeid { get; set; }
        public Nullable<int> familiaid { get; set; }
        public Nullable<int> servicoid { get; set; }
        public string labelok { get; set; }
        public string labelnok { get; set; }
        public Nullable<int> pontuacaook { get; set; }
        public Nullable<int> pontuacaonok { get; set; }
        public string obrigatoriofotositem { get; set; }
        public string obs { get; set; }
        public string ativo { get; set; }
    
        public virtual FamiliasProdutos FamiliasProdutos { get; set; }
        public virtual FinalidadesOrdensServicos FinalidadesOrdensServicos { get; set; }
        public virtual Servicos Servicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsFamiliasProdutos> ChecklistsFamiliasProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsGrupos> ChecklistsGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsProdutos> ChecklistsProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosChecklists> OrdensServicosChecklists { get; set; }
    }
}
