//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistsItens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistsItens()
        {
            this.ChecklistsItensOpcoes = new HashSet<ChecklistsItensOpcoes>();
        }
    
        public int id { get; set; }
        public int checklistgrupoid { get; set; }
        public int ordem { get; set; }
        public string item { get; set; }
        public string detalheitem { get; set; }
        public string tipoitem { get; set; }
        public string obrigatoriofotositem { get; set; }
        public string obrigatoriovideoitem { get; set; }
        public string labelok { get; set; }
        public string labelnok { get; set; }
    
        public virtual ChecklistsGrupos ChecklistsGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsItensOpcoes> ChecklistsItensOpcoes { get; set; }
    }
}
