//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistsItensStatusOportunidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistsItensStatusOportunidades()
        {
            this.ChecklistsItensStatusOportunidadesOpcoes = new HashSet<ChecklistsItensStatusOportunidadesOpcoes>();
        }
    
        public int id { get; set; }
        public int statusid { get; set; }
        public int ordem { get; set; }
        public string item { get; set; }
        public string detalheitem { get; set; }
        public string tipoitem { get; set; }
        public string ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsItensStatusOportunidadesOpcoes> ChecklistsItensStatusOportunidadesOpcoes { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
    }
}
