//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistsGrupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistsGrupos()
        {
            this.ChecklistsItens = new HashSet<ChecklistsItens>();
        }
    
        public int id { get; set; }
        public int checklistid { get; set; }
        public int ordem { get; set; }
        public string descricao { get; set; }
        public string obs { get; set; }
    
        public virtual Checklists Checklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsItens> ChecklistsItens { get; set; }
    }
}
