//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistsProdutos
    {
        public int id { get; set; }
        public int checklistid { get; set; }
        public int produtoid { get; set; }
    
        public virtual Checklists Checklists { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
