//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunicadosFamilias
    {
        public int id { get; set; }
        public int comunicadoid { get; set; }
        public int familiaid { get; set; }
    
        public virtual Comunicados Comunicados { get; set; }
        public virtual FamiliasProdutos FamiliasProdutos { get; set; }
    }
}
