//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunicados()
        {
            this.ComunicadosFamilias = new HashSet<ComunicadosFamilias>();
            this.ComunicadosPostosAutorizados = new HashSet<ComunicadosPostosAutorizados>();
            this.ComunicadosProdutos = new HashSet<ComunicadosProdutos>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string mensagem { get; set; }
        public string exibirtelainicial { get; set; }
        public string ativo { get; set; }
        public Nullable<int> fileid { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosFamilias> ComunicadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosPostosAutorizados> ComunicadosPostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosProdutos> ComunicadosProdutos { get; set; }
    }
}
