//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicoesPagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CondicoesPagamento()
        {
            this.Entidades = new HashSet<Entidades>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public int tabelaprecoid { get; set; }
        public decimal valorminimo { get; set; }
        public string codigoerp { get; set; }
        public string ativo { get; set; }
        public Nullable<decimal> percentualacrescimo { get; set; }
        public string char1 { get; set; }
        public Nullable<decimal> percentualdesconto { get; set; }
    
        public virtual TabelasPrecos TabelasPrecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
