//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumidores()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.Chats = new HashSet<Chats>();
            this.ConsumidoresComentarios = new HashSet<ConsumidoresComentarios>();
            this.ProdutosConsumidores = new HashSet<ProdutosConsumidores>();
            this.Contatos = new HashSet<Contatos>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.NPSRegistros = new HashSet<NPSRegistros>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public string cpfcnpj { get; set; }
        public string nomerazaosocial { get; set; }
        public string telefone { get; set; }
        public string rginscricaoestadual { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public string consumidorfinal { get; set; }
        public string contrato { get; set; }
        public string numerocontrato { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string newsletter { get; set; }
        public string referencia { get; set; }
        public string telefone2 { get; set; }
        public string pais { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string contacorrente { get; set; }
        public string telefone3 { get; set; }
        public string char1 { get; set; }
        public string origemcadastro { get; set; }
        public string telefonepais { get; set; }
        public string telefonesiglapais { get; set; }
        public string telefonedialcodepais { get; set; }
        public string telefone2pais { get; set; }
        public string telefone2siglapais { get; set; }
        public string telefone2dialcodepais { get; set; }
        public string telefone3pais { get; set; }
        public string telefone3siglapais { get; set; }
        public string telefone3dialcodepais { get; set; }
        public string customeridpagarme { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public Nullable<int> regiaoid { get; set; }
        public Nullable<long> telefonenumber { get; set; }
        public Nullable<long> telefone2number { get; set; }
        public Nullable<long> telefone3number { get; set; }
        public string obsvisao360 { get; set; }
        public string nomerazaosocial_normalizado { get; set; }
        public string cidade_normalizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual Regioes Regioes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumidoresComentarios> ConsumidoresComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosConsumidores> ProdutosConsumidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatos> Contatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPSRegistros> NPSRegistros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
