//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosCorreios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratosCorreios()
        {
            this.ServicosContratosCorreios = new HashSet<ServicosContratosCorreios>();
        }
    
        public int id { get; set; }
        public string cnpj { get; set; }
        public string codigoadministrativo { get; set; }
        public string contrato { get; set; }
        public string cartaopostagem { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosContratosCorreios> ServicosContratosCorreios { get; set; }
    }
}
