//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContatosLayoutImportacao
    {
        public int id { get; set; }
        public string nomecampo { get; set; }
        public Nullable<int> campospersonalizadosid { get; set; }
        public Nullable<int> ordem { get; set; }
    
        public virtual CamposPersonalizados CamposPersonalizados { get; set; }
    }
}
