//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefeitosReclamados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefeitosReclamados()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.AtendimentosDefeitosReclamados = new HashSet<AtendimentosDefeitosReclamados>();
            this.AtendimentosProdutos = new HashSet<AtendimentosProdutos>();
            this.DefeitosReclamadosFamilias = new HashSet<DefeitosReclamadosFamilias>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.OrdensServicosDefeitosReclamados = new HashSet<OrdensServicosDefeitosReclamados>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string referencia { get; set; }
        public string char1 { get; set; }
        public string naodisponibilizarnoaplicativo { get; set; }
        public string enviaauditoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosDefeitosReclamados> AtendimentosDefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosProdutos> AtendimentosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosReclamadosFamilias> DefeitosReclamadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosReclamados> OrdensServicosDefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
    }
}
