//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefeitosConstatadosFamilias
    {
        public int id { get; set; }
        public int familiaid { get; set; }
        public int defeitoconstatadoid { get; set; }
    
        public virtual DefeitosConstatados DefeitosConstatados { get; set; }
        public virtual FamiliasProdutos FamiliasProdutos { get; set; }
    }
}
