//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefeitosConstatados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefeitosConstatados()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.DefeitosConstatadosFamilias = new HashSet<DefeitosConstatadosFamilias>();
            this.DefeitosConstatadosRestritos = new HashSet<DefeitosConstatadosRestritos>();
            this.OrdensServicosDefeitosConstatados = new HashSet<OrdensServicosDefeitosConstatados>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string referencia { get; set; }
        public string naonecessariotrocarpecas { get; set; }
        public string char1 { get; set; }
        public string enviaauditoria { get; set; }
        public Nullable<decimal> valormaodeobra { get; set; }
        public string disponivelsomentefabricante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosConstatadosFamilias> DefeitosConstatadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosConstatadosRestritos> DefeitosConstatadosRestritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosConstatados> OrdensServicosDefeitosConstatados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
    }
}
