//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefeitosConstatadosRestritosFamiliasPecas
    {
        public int id { get; set; }
        public int defeitoconstatadorestritoid { get; set; }
        public int familiapecaid { get; set; }
    
        public virtual DefeitosConstatadosRestritos DefeitosConstatadosRestritos { get; set; }
        public virtual FamiliasPecas FamiliasPecas { get; set; }
    }
}
