//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DePara
    {
        public int id { get; set; }
        public int pecaidde { get; set; }
        public int pecaidpara { get; set; }
        public System.DateTime validade { get; set; }
    
        public virtual Pecas Pecas { get; set; }
        public virtual Pecas Pecas1 { get; set; }
    }
}
