//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentos()
        {
            this.ChatGPTDados = new HashSet<ChatGPTDados>();
            this.DocumentosProdutos = new HashSet<DocumentosProdutos>();
        }
    
        public int id { get; set; }
        public int tipoid { get; set; }
        public Nullable<int> fileid { get; set; }
        public string nome { get; set; }
        public string obs { get; set; }
        public string linkvideoyoutube { get; set; }
        public string estruturaversionadareferencia { get; set; }
        public string ativo { get; set; }
        public string disponibilizarnoaplicativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatGPTDados> ChatGPTDados { get; set; }
        public virtual TiposDocumentos TiposDocumentos { get; set; }
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosProdutos> DocumentosProdutos { get; set; }
    }
}
