//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnderecoProduto
    {
        public int id { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public string descricao { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
