//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidades()
        {
            this.AtendimentosEntidades = new HashSet<AtendimentosEntidades>();
            this.Atividades = new HashSet<Atividades>();
            this.CamposPersonalizadosEntidades = new HashSet<CamposPersonalizadosEntidades>();
            this.Contatos = new HashSet<Contatos>();
            this.Entidades1 = new HashSet<Entidades>();
            this.EntidadesComentarios = new HashSet<EntidadesComentarios>();
            this.EntidadesDadosExternos = new HashSet<EntidadesDadosExternos>();
            this.EntidadesEnderecosAdicionais2 = new HashSet<EntidadesEnderecosAdicionais>();
            this.EntidadesInteracoes = new HashSet<EntidadesInteracoes>();
            this.EntidadesSegmentos = new HashSet<EntidadesSegmentos>();
            this.EntidadesTabelasPrecosVenda = new HashSet<EntidadesTabelasPrecosVenda>();
            this.EntidadesTags = new HashSet<EntidadesTags>();
            this.ExtratosLotes = new HashSet<ExtratosLotes>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.NaoConformidadesEntidades = new HashSet<NaoConformidadesEntidades>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OrdensServicosEntidades = new HashSet<OrdensServicosEntidades>();
            this.Pedidos = new HashSet<Pedidos>();
            this.ReferenciasProdutosEntidades = new HashSet<ReferenciasProdutosEntidades>();
        }
    
        public int id { get; set; }
        public int tipoentidadeid { get; set; }
        public string referencia { get; set; }
        public string cpfcnpj { get; set; }
        public string nome { get; set; }
        public string razaosocial { get; set; }
        public string telefone { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public string rginscricaoestadual { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string email { get; set; }
        public string telefonepais { get; set; }
        public string telefonesiglapais { get; set; }
        public string telefonedialcodepais { get; set; }
        public string telefone2pais { get; set; }
        public string telefone2siglapais { get; set; }
        public string telefone2dialcodepais { get; set; }
        public string telefone3pais { get; set; }
        public string telefone3siglapais { get; set; }
        public string telefone3dialcodepais { get; set; }
        public Nullable<int> regiaoid { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public string disponivelmodulonegocios { get; set; }
        public Nullable<int> entidadeidmatriz { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string obsvisao360 { get; set; }
        public string nome_normalizado { get; set; }
        public string razaosocial_normalizado { get; set; }
        public string cidade_normalizado { get; set; }
        public Nullable<long> telefonenumber { get; set; }
        public Nullable<long> telefone2number { get; set; }
        public Nullable<long> telefone3number { get; set; }
        public Nullable<int> usuarioidvendedor { get; set; }
        public string usuarionomevendedor { get; set; }
        public Nullable<int> representanteid { get; set; }
        public Nullable<int> transportadoraid { get; set; }
        public Nullable<int> transportadoraidredespacho { get; set; }
        public Nullable<int> condicaopagamentoid { get; set; }
        public Nullable<int> naturezaoperacaoid { get; set; }
        public string integradoerp { get; set; }
        public Nullable<int> enderecoentregaid { get; set; }
        public Nullable<int> enderecocobrancaid { get; set; }
        public string origem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosEntidades> AtendimentosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividades> Atividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosEntidades> CamposPersonalizadosEntidades { get; set; }
        public virtual CondicoesPagamento CondicoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatos> Contatos { get; set; }
        public virtual EntidadesEnderecosAdicionais EntidadesEnderecosAdicionais { get; set; }
        public virtual EntidadesEnderecosAdicionais EntidadesEnderecosAdicionais1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades1 { get; set; }
        public virtual Entidades Entidades2 { get; set; }
        public virtual NaturezaOperacao NaturezaOperacao { get; set; }
        public virtual Regioes Regioes { get; set; }
        public virtual Representantes Representantes { get; set; }
        public virtual TiposEntidades TiposEntidades { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
        public virtual Transportadoras Transportadoras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesComentarios> EntidadesComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesDadosExternos> EntidadesDadosExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesEnderecosAdicionais> EntidadesEnderecosAdicionais2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesInteracoes> EntidadesInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesSegmentos> EntidadesSegmentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesTabelasPrecosVenda> EntidadesTabelasPrecosVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesTags> EntidadesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtratosLotes> ExtratosLotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesEntidades> NaoConformidadesEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosEntidades> OrdensServicosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciasProdutosEntidades> ReferenciasProdutosEntidades { get; set; }
    }
}
