//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstruturasVersionadasCapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstruturasVersionadasCapa()
        {
            this.EstruturasVersionadas = new HashSet<EstruturasVersionadas>();
            this.ProdutosConsumidores = new HashSet<ProdutosConsumidores>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
            this.Refurbished = new HashSet<Refurbished>();
        }
    
        public int id { get; set; }
        public int produtoid { get; set; }
        public string modelo { get; set; }
        public long loteinicial { get; set; }
        public long lotefinal { get; set; }
        public string referencia { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public Nullable<System.DateTime> datafaturamento { get; set; }
        public Nullable<System.DateTime> dataproducao { get; set; }
        public string char1 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public string loteserie { get; set; }
        public string notafiscal { get; set; }
        public string char2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstruturasVersionadas> EstruturasVersionadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosConsumidores> ProdutosConsumidores { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refurbished> Refurbished { get; set; }
    }
}
