//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstruturasVersionadas
    {
        public int id { get; set; }
        public int estruturaversionadacapaid { get; set; }
        public int pecaid { get; set; }
        public decimal qtde { get; set; }
        public int ordem { get; set; }
        public string referencia { get; set; }
    
        public virtual EstruturasVersionadasCapa EstruturasVersionadasCapa { get; set; }
        public virtual Pecas Pecas { get; set; }
    }
}
