//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcessoesMaoDeObra
    {
        public int id { get; set; }
        public int postoid { get; set; }
        public Nullable<int> produtoid { get; set; }
        public Nullable<int> familiaid { get; set; }
        public string tipo { get; set; }
        public decimal valor { get; set; }
        public string ativo { get; set; }
        public Nullable<int> finalidadeid { get; set; }
    
        public virtual FamiliasProdutos FamiliasProdutos { get; set; }
        public virtual FinalidadesOrdensServicos FinalidadesOrdensServicos { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
