//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtratosLotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtratosLotes()
        {
            this.Extratos = new HashSet<Extratos>();
            this.ExtratosLotesTags = new HashSet<ExtratosLotesTags>();
        }
    
        public long id { get; set; }
        public Nullable<int> postoid { get; set; }
        public Nullable<int> entidadeid { get; set; }
        public Nullable<System.DateTime> datageracao { get; set; }
        public System.DateTime data { get; set; }
        public decimal totalos { get; set; }
        public decimal totalavulso { get; set; }
        public decimal valortotal { get; set; }
        public decimal acrescimo { get; set; }
        public decimal desconto { get; set; }
        public decimal valorliquido { get; set; }
        public Nullable<System.DateTime> datavencimento { get; set; }
        public string notafiscal { get; set; }
        public Nullable<int> notafiscalfileid { get; set; }
        public Nullable<System.DateTime> datauploadnotafiscal { get; set; }
        public Nullable<System.DateTime> datapagamento { get; set; }
        public string status { get; set; }
        public string obs { get; set; }
        public string exportado { get; set; }
        public Nullable<System.DateTime> dataliberacao { get; set; }
        public Nullable<System.DateTime> datacancelamento { get; set; }
        public Nullable<int> usuarioidliberacao { get; set; }
        public string usuarionomeliberacao { get; set; }
        public Nullable<int> comprovantepagamentofileid { get; set; }
        public string numeroreferenciaexterna { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extratos> Extratos { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtratosLotesTags> ExtratosLotesTags { get; set; }
    }
}
