//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extratos
    {
        public int id { get; set; }
        public long extratoloteid { get; set; }
        public System.DateTime data { get; set; }
        public string tipo { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> tipolancamentoavulsoid { get; set; }
        public decimal valor { get; set; }
        public string status { get; set; }
        public string obs { get; set; }
    
        public virtual ExtratosLotes ExtratosLotes { get; set; }
        public virtual TiposLancamentosAvulsos TiposLancamentosAvulsos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
