//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliasProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamiliasProdutos()
        {
            this.ArvoreDiagnosticosFamilias = new HashSet<ArvoreDiagnosticosFamilias>();
            this.Checklists = new HashSet<Checklists>();
            this.ChecklistsFamiliasProdutos = new HashSet<ChecklistsFamiliasProdutos>();
            this.ComunicadosFamilias = new HashSet<ComunicadosFamilias>();
            this.DefeitosConstatadosFamilias = new HashSet<DefeitosConstatadosFamilias>();
            this.DefeitosReclamadosFamilias = new HashSet<DefeitosReclamadosFamilias>();
            this.ExcessoesMaoDeObra = new HashSet<ExcessoesMaoDeObra>();
            this.Produtos = new HashSet<Produtos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string notificarconsumidoraposconserto { get; set; }
        public string referencia { get; set; }
        public string familiainterna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArvoreDiagnosticosFamilias> ArvoreDiagnosticosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklists> Checklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsFamiliasProdutos> ChecklistsFamiliasProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosFamilias> ComunicadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosConstatadosFamilias> DefeitosConstatadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosReclamadosFamilias> DefeitosReclamadosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcessoesMaoDeObra> ExcessoesMaoDeObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produtos> Produtos { get; set; }
    }
}
