//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliasPecas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamiliasPecas()
        {
            this.DefeitosConstatadosRestritosFamiliasPecas = new HashSet<DefeitosConstatadosRestritosFamiliasPecas>();
            this.Pecas = new HashSet<Pecas>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string referencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefeitosConstatadosRestritosFamiliasPecas> DefeitosConstatadosRestritosFamiliasPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pecas> Pecas { get; set; }
    }
}
