//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filtros()
        {
            this.FiltrosCampos = new HashSet<FiltrosCampos>();
        }
    
        public int id { get; set; }
        public string origem { get; set; }
        public string descricao { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public string padrao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiltrosCampos> FiltrosCampos { get; set; }
    }
}
