//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalidadesOrdensServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinalidadesOrdensServicos()
        {
            this.Checklists = new HashSet<Checklists>();
            this.ExcessoesMaoDeObra = new HashSet<ExcessoesMaoDeObra>();
            this.FinalidadesOrdensServicosServicosAdicionaisObrigatorios = new HashSet<FinalidadesOrdensServicosServicosAdicionaisObrigatorios>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.PostosAutorizadosFinalidadesOrdensServicos = new HashSet<PostosAutorizadosFinalidadesOrdensServicos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string padrao { get; set; }
        public string defeitoobrigatorio { get; set; }
        public string notafiscalobrigatoriaabertura { get; set; }
        public string notafiscalobrigatoriafinalizacao { get; set; }
        public string identificarpostomaisproximoabertura { get; set; }
        public string considerarindicadores { get; set; }
        public string permitetecnicofinalizar { get; set; }
        public string permitesolicitarpecasemcadastro { get; set; }
        public string checksobrigatoriosaplicativo { get; set; }
        public string notificarconsumidoraposconserto { get; set; }
        public string semprebuscarpecasestruturapadrao { get; set; }
        public string char1 { get; set; }
        public string defeitoobrigatoriopeca { get; set; }
        public string obrigatoriodefeitoreclamadocadastrado { get; set; }
        public string obrigatoriodefeitoreclamadodigitado { get; set; }
        public string validarlimitepecasdistintasgarantia { get; set; }
        public string disponivelparapostoautorizado { get; set; }
        public string permiteprelancamento { get; set; }
        public string permiteprodutogarantiaexpirada { get; set; }
        public string validarestruturaversionada { get; set; }
        public string solicitardataproducaoloteinexistente { get; set; }
        public string aceiteconsumidorobrigatoriopagamento { get; set; }
        public string gerarrefurbished { get; set; }
        public string validargarantia { get; set; }
        public string assinaturaobrigatoriaaplicativo { get; set; }
        public string permitealterarprodutoaplicativo { get; set; }
        public string solicitardataproducaoinexistente { get; set; }
        public string obrigatorioagendamento { get; set; }
        public string habilitaravaliacaoatendimento { get; set; }
        public string bloquearduplicidade { get; set; }
        public string obrigatoriorelatovisitascomplementares { get; set; }
        public string ativo { get; set; }
        public string notificarconclusao { get; set; }
        public Nullable<int> periodicidadeemdiasnotificacao { get; set; }
        public Nullable<int> numeroidnotificacao { get; set; }
        public string permitealteraragendamentoaplicativo { get; set; }
        public string notificardeslocamento { get; set; }
        public string encerraratendimentofinalizacaoordem { get; set; }
        public string gerarauditoriareincidencianotafiscalloteserie { get; set; }
        public string gerarauditoriareincidencialoteserie { get; set; }
        public string permitereabrirordemcanceladapelofabricante { get; set; }
        public string permitecheckssomentecomdeslocamentorealizado { get; set; }
        public string permiteapenasumdeslocamento { get; set; }
        public string permitebotaocapturaraplicativosomenteentrechecks { get; set; }
        public string permitepreenchimentochecklistsomenteentrechecks { get; set; }
        public string bloquearalteracaoquantidadedevolucaopeca { get; set; }
        public string permiteeditarapontamentos { get; set; }
        public string permitetransmissaosomentecomretornorealizado { get; set; }
        public Nullable<int> permitecheckssomentedentrodoraio { get; set; }
        public string necessarioliberacaoposto { get; set; }
        public string bloquearretornarstatusparaanalise { get; set; }
        public string bloquearlancamentoforadadatadoagendamento { get; set; }
        public string obrigatoriotag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklists> Checklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcessoesMaoDeObra> ExcessoesMaoDeObra { get; set; }
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadesOrdensServicosServicosAdicionaisObrigatorios> FinalidadesOrdensServicosServicosAdicionaisObrigatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosFinalidadesOrdensServicos> PostosAutorizadosFinalidadesOrdensServicos { get; set; }
    }
}
