//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalidadesOrdensServicosServicosGeraisAdicionaisObrigatorios
    {
        public int id { get; set; }
        public int finalidadeordemgeralid { get; set; }
        public int servicoadicionalid { get; set; }
    
        public virtual FinalidadesOrdensServicosGerais FinalidadesOrdensServicosGerais { get; set; }
        public virtual ServicosAdicionais ServicosAdicionais { get; set; }
    }
}
