//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluxosAtendimentoMessagingCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FluxosAtendimentoMessagingCenter()
        {
            this.FluxosAtendimentoMessagingCenterEtapas = new HashSet<FluxosAtendimentoMessagingCenterEtapas>();
            this.FluxosAtendimentoMessagingCenterPadraoUsuarios = new HashSet<FluxosAtendimentoMessagingCenterPadraoUsuarios>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FluxosAtendimentoMessagingCenterEtapas> FluxosAtendimentoMessagingCenterEtapas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FluxosAtendimentoMessagingCenterPadraoUsuarios> FluxosAtendimentoMessagingCenterPadraoUsuarios { get; set; }
    }
}
