//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluxosAtendimentoMessagingCenterEtapas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FluxosAtendimentoMessagingCenterEtapas()
        {
            this.Chats = new HashSet<Chats>();
            this.PaineisOportunidadesFluxosAtendimento = new HashSet<PaineisOportunidadesFluxosAtendimento>();
        }
    
        public int id { get; set; }
        public int fluxoatendimentoid { get; set; }
        public string etapa { get; set; }
        public int ordem { get; set; }
        public string ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual FluxosAtendimentoMessagingCenter FluxosAtendimentoMessagingCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesFluxosAtendimento> PaineisOportunidadesFluxosAtendimento { get; set; }
    }
}
