//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulariosHTML
    {
        public int id { get; set; }
        public string hash { get; set; }
        public System.DateTime datacriacao { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public Nullable<int> logofileid { get; set; }
        public Nullable<int> capafileid { get; set; }
        public string customcss { get; set; }
        public string customjavascript { get; set; }
        public int usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string html { get; set; }
        public string publico { get; set; }
        public int acessos { get; set; }
        public Nullable<System.DateTime> dataultimaalteracao { get; set; }
        public Nullable<int> usuarioidultimaalteracao { get; set; }
        public string usuarionomeultimaalteracao { get; set; }
        public string ocultarlogo { get; set; }
        public string ocultarcapa { get; set; }
        public string customhtml { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
    }
}
