//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposCallCenterUsuarios
    {
        public int id { get; set; }
        public int grupocallcenterid { get; set; }
        public int usuarioid { get; set; }
        public string nome { get; set; }
        public string excecaodistribuicaoautomaticaatendimento { get; set; }
        public string excecaodistribuicaoautomaticamessagingcenter { get; set; }
    
        public virtual GruposCallCenter GruposCallCenter { get; set; }
    }
}
