//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposCallCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GruposCallCenter()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.AtendimentosInteracoes = new HashSet<AtendimentosInteracoes>();
            this.Chats = new HashSet<Chats>();
            this.Chats1 = new HashSet<Chats>();
            this.ChatsTranferencias = new HashSet<ChatsTranferencias>();
            this.GruposCallCenter1 = new HashSet<GruposCallCenter>();
            this.GruposCallCenterUsuarios = new HashSet<GruposCallCenterUsuarios>();
            this.IntegracoesMarketplaces = new HashSet<IntegracoesMarketplaces>();
            this.ModelosAtendimentos = new HashSet<ModelosAtendimentos>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string conta { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public string disponivelchat { get; set; }
        public Nullable<int> codigochat { get; set; }
        public Nullable<int> numerowhatsappid { get; set; }
        public Nullable<int> grupocallcenterpaiid { get; set; }
        public string distribuicaoautomaticaconversas { get; set; }
        public Nullable<int> tempoencerramentoautomatico { get; set; }
        public string mensagemencerramentoautomatico { get; set; }
        public string ativo { get; set; }
        public Nullable<int> statusatendimentoid { get; set; }
        public string distribuicaoautomaticaatendimentos { get; set; }
        public string habilitaravaliacaoatendimento { get; set; }
        public string mensagemfinal { get; set; }
        public string respostaautomaticarecebimentoemail { get; set; }
        public string smtp { get; set; }
        public Nullable<bool> smtpssl { get; set; }
        public Nullable<int> smtpporta { get; set; }
        public string pop { get; set; }
        public Nullable<bool> popssl { get; set; }
        public Nullable<int> popporta { get; set; }
        public string imap { get; set; }
        public Nullable<bool> imapssl { get; set; }
        public Nullable<int> imapporta { get; set; }
        public string clientemail { get; set; }
        public string distribuicaoautomaticaconversassomenteparausuariosonline { get; set; }
        public string considerarinatividadeusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosInteracoes> AtendimentosInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsTranferencias> ChatsTranferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposCallCenter> GruposCallCenter1 { get; set; }
        public virtual GruposCallCenter GruposCallCenter2 { get; set; }
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
        public virtual StatusAtendimentos StatusAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposCallCenterUsuarios> GruposCallCenterUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegracoesMarketplaces> IntegracoesMarketplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelosAtendimentos> ModelosAtendimentos { get; set; }
    }
}
