//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IASConsumoTokens
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> chatgptid { get; set; }
        public string input_text { get; set; }
        public string threadid { get; set; }
        public Nullable<int> usuarioid { get; set; }
        public string usuarionome { get; set; }
        public Nullable<int> numeroid { get; set; }
        public Nullable<int> contatoid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public int in_tokens { get; set; }
        public int out_tokens { get; set; }
        public int total_tokens { get; set; }
        public string output_text { get; set; }
        public string modelo { get; set; }
        public Nullable<long> cached_tokens { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual ChatGPT ChatGPT { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
    }
}
