//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.JobItem = new HashSet<JobItem>();
        }
    
        public int id { get; set; }
        public System.DateTime datacriacao { get; set; }
        public int usuarioidcriacao { get; set; }
        public string usuarionomecriacao { get; set; }
        public string tipojob { get; set; }
        public Nullable<bool> download { get; set; }
        public string ContentType { get; set; }
        public string filepath { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dataexecucao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobItem> JobItem { get; set; }
    }
}
