//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosPerdasOportunidadesStatusRestritos
    {
        public int id { get; set; }
        public int motivoperdaid { get; set; }
        public int statusid { get; set; }
    
        public virtual MotivosPerdasOportunidades MotivosPerdasOportunidades { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
    }
}
