//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovtoEstoque
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int postoid { get; set; }
        public Nullable<int> pedidoid { get; set; }
        public Nullable<int> ordemprodutoid { get; set; }
        public int pecaid { get; set; }
        public decimal quantidade { get; set; }
        public string tipo { get; set; }
        public string obs { get; set; }
    
        public virtual OrdensServicosProdutos OrdensServicosProdutos { get; set; }
        public virtual Pecas Pecas { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
    }
}
