//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaoConformidadesEntidades
    {
        public int id { get; set; }
        public int naoconformidadeid { get; set; }
        public int entidadeid { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        public virtual NaoConformidades NaoConformidades { get; set; }
    }
}
