//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaoConformidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaoConformidades()
        {
            this.NaoConformidadesAtendimentos = new HashSet<NaoConformidadesAtendimentos>();
            this.NaoConformidadesEntidades = new HashSet<NaoConformidadesEntidades>();
            this.NaoConformidadesOrdensServicos = new HashSet<NaoConformidadesOrdensServicos>();
        }
    
        public int id { get; set; }
        public System.DateTime datacriacao { get; set; }
        public int usuarioidcriacao { get; set; }
        public string usuarionomecriacao { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public int produtoid { get; set; }
        public string loteserie { get; set; }
        public Nullable<int> estruturaversionadacapaid { get; set; }
        public Nullable<int> origemnaoconformidadeid { get; set; }
        public Nullable<int> pecaid { get; set; }
        public string descricaofalhaocorrida { get; set; }
        public string inspecao { get; set; }
        public string causa { get; set; }
        public string acao { get; set; }
        public string laudo { get; set; }
        public Nullable<int> conclusaonaoconformidadeid { get; set; }
        public Nullable<System.DateTime> dataconclusao { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> prazoconclusao { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public Nullable<int> entidadeid { get; set; }
    
        public virtual ConclusoesNaoConformidades ConclusoesNaoConformidades { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual EstruturasVersionadasCapa EstruturasVersionadasCapa { get; set; }
        public virtual OrigensNaoConformidades OrigensNaoConformidades { get; set; }
        public virtual Pecas Pecas { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesAtendimentos> NaoConformidadesAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesEntidades> NaoConformidadesEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesOrdensServicos> NaoConformidadesOrdensServicos { get; set; }
    }
}
