//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaturezaOperacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaturezaOperacao()
        {
            this.Entidades = new HashSet<Entidades>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public string tipo { get; set; }
        public string cfop { get; set; }
        public string consumidorfinal { get; set; }
        public string contribuinteicms { get; set; }
        public string tributacaoicms { get; set; }
        public decimal aliquotaicms { get; set; }
        public string tributacaoipi { get; set; }
        public decimal aliquotaipi { get; set; }
        public string tributacaopis { get; set; }
        public decimal aliquotapis { get; set; }
        public string retencaopis { get; set; }
        public string tributacaocofins { get; set; }
        public decimal aliquotacofins { get; set; }
        public string retencaocofins { get; set; }
        public string retencaocsll { get; set; }
        public string retencaoirrf { get; set; }
        public string obs { get; set; }
        public string ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
