//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisPendenciasDevolucaoInteracoes
    {
        public int id { get; set; }
        public int notafiscalpendenciadevolucaoid { get; set; }
        public System.DateTime data { get; set; }
        public int usuarioidremetente { get; set; }
        public string remetente { get; set; }
        public string mensagem { get; set; }
    
        public virtual NotasFiscaisPendenciasDevolucao NotasFiscaisPendenciasDevolucao { get; set; }
    }
}
