//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisPendenciasDevolucaoPecas
    {
        public int id { get; set; }
        public int notafiscalpendenciadevolucaoid { get; set; }
        public int ordempecaid { get; set; }
        public decimal quantidadedevolvida { get; set; }
        public string pecarecebida { get; set; }
    
        public virtual NotasFiscaisPendenciasDevolucao NotasFiscaisPendenciasDevolucao { get; set; }
        public virtual OrdensServicosPecas OrdensServicosPecas { get; set; }
    }
}
