//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisProdutos
    {
        public int id { get; set; }
        public int notafiscalid { get; set; }
        public int produtoid { get; set; }
        public decimal quantidade { get; set; }
        public Nullable<decimal> precotabela { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public string obs { get; set; }
    
        public virtual NotasFiscais NotasFiscais { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
