//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisPendenciasDevolucao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasFiscaisPendenciasDevolucao()
        {
            this.ChatsOnlineUsersNotasFiscaisPendenciasDevolucao = new HashSet<ChatsOnlineUsersNotasFiscaisPendenciasDevolucao>();
            this.NotasFiscaisPendenciasDevolucaoAutorizacaoPostagem = new HashSet<NotasFiscaisPendenciasDevolucaoAutorizacaoPostagem>();
            this.NotasFiscaisPendenciasDevolucaoInteracoes = new HashSet<NotasFiscaisPendenciasDevolucaoInteracoes>();
            this.NotasFiscaisPendenciasDevolucaoPecas = new HashSet<NotasFiscaisPendenciasDevolucaoPecas>();
        }
    
        public int id { get; set; }
        public string notafiscal { get; set; }
        public System.DateTime datafaturamento { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dataconferencia { get; set; }
        public Nullable<int> usuarioidconferencia { get; set; }
        public string usuarionomeconferencia { get; set; }
        public int volumes { get; set; }
        public Nullable<int> notafiscalfileid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsOnlineUsersNotasFiscaisPendenciasDevolucao> ChatsOnlineUsersNotasFiscaisPendenciasDevolucao { get; set; }
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPendenciasDevolucaoAutorizacaoPostagem> NotasFiscaisPendenciasDevolucaoAutorizacaoPostagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPendenciasDevolucaoInteracoes> NotasFiscaisPendenciasDevolucaoInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPendenciasDevolucaoPecas> NotasFiscaisPendenciasDevolucaoPecas { get; set; }
    }
}
