//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasFiscais()
        {
            this.NotasFiscaisOcorrencias = new HashSet<NotasFiscaisOcorrencias>();
            this.NotasFiscaisPecas = new HashSet<NotasFiscaisPecas>();
            this.NotasFiscaisProdutos = new HashSet<NotasFiscaisProdutos>();
        }
    
        public int id { get; set; }
        public int pedidoid { get; set; }
        public string notafiscal { get; set; }
        public System.DateTime datafaturamento { get; set; }
        public string tipofaturamento { get; set; }
        public string transportador { get; set; }
        public string chaveacesso { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisOcorrencias> NotasFiscaisOcorrencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPecas> NotasFiscaisPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisProdutos> NotasFiscaisProdutos { get; set; }
    }
}
