//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacoes
    {
        public int id { get; set; }
        public int usuarioid { get; set; }
        public string texto { get; set; }
        public string lida { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> chatmensagemid { get; set; }
    }
}
