//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacoesPreferenciasUsuarios
    {
        public int id { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public string notificacao { get; set; }
        public string descricao { get; set; }
        public string central { get; set; }
        public string email { get; set; }
        public string popup { get; set; }
        public string app { get; set; }
    }
}
