//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPSRegistros
    {
        public int id { get; set; }
        public string token { get; set; }
        public System.DateTime datageracao { get; set; }
        public int npsid { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public Nullable<int> nota { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> dataresposta { get; set; }
        public Nullable<int> contatoid { get; set; }
        public string enviadowhatsapp { get; set; }
        public string enviadoemail { get; set; }
    
        public virtual Consumidores Consumidores { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual NPS NPS { get; set; }
    }
}
