//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumerosWhatsAppSubFilasSQS
    {
        public int id { get; set; }
        public int numeroid { get; set; }
        public string ddds { get; set; }
        public string subfila { get; set; }
        public string obs { get; set; }
        public Nullable<int> digitostelefone { get; set; }
    
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
    }
}
