//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumerosWhatsApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NumerosWhatsApp()
        {
            this.Campanhas = new HashSet<Campanhas>();
            this.Chamadas = new HashSet<Chamadas>();
            this.Chats = new HashSet<Chats>();
            this.ChatsCanaisUsuarios = new HashSet<ChatsCanaisUsuarios>();
            this.FinalidadesOrdensServicos = new HashSet<FinalidadesOrdensServicos>();
            this.FinalidadesOrdensServicosGerais = new HashSet<FinalidadesOrdensServicosGerais>();
            this.GruposCallCenter = new HashSet<GruposCallCenter>();
            this.IASConsumoTokens = new HashSet<IASConsumoTokens>();
            this.NumerosWhatsAppSubFilasSQS = new HashSet<NumerosWhatsAppSubFilasSQS>();
            this.OportunidadesParametrosGatewayPagamento = new HashSet<OportunidadesParametrosGatewayPagamento>();
            this.ParametrosNegocios = new HashSet<ParametrosNegocios>();
            this.TemplatesMeta = new HashSet<TemplatesMeta>();
        }
    
        public int id { get; set; }
        public string telefone { get; set; }
        public string whatsappid { get; set; }
        public string senhatoken { get; set; }
        public Nullable<System.DateTime> datahoraultimaverificacao { get; set; }
        public string status { get; set; }
        public string host { get; set; }
        public string mensageminicial { get; set; }
        public string mensagemfinal { get; set; }
        public string ativo { get; set; }
        public Nullable<int> deviceid { get; set; }
        public string webhookendpoint { get; set; }
        public Nullable<bool> usebotpress { get; set; }
        public string botpresshost { get; set; }
        public string botpressid { get; set; }
        public Nullable<bool> useappandroid { get; set; }
        public string zapi { get; set; }
        public Nullable<int> chatbotid { get; set; }
        public string domingoatende { get; set; }
        public string domingohorarioiniciomanha { get; set; }
        public string domingohorariofimmanha { get; set; }
        public string domingohorarioiniciotarde { get; set; }
        public string domingohorariofimtarde { get; set; }
        public string domingohorarioinicionoite { get; set; }
        public string domingohorariofimnoite { get; set; }
        public string segundaatende { get; set; }
        public string segundahorarioiniciomanha { get; set; }
        public string segundahorariofimmanha { get; set; }
        public string segundahorarioiniciotarde { get; set; }
        public string segundahorariofimtarde { get; set; }
        public string segundahorarioinicionoite { get; set; }
        public string segundahorariofimnoite { get; set; }
        public string tercaatende { get; set; }
        public string tercahorarioiniciomanha { get; set; }
        public string tercahorariofimmanha { get; set; }
        public string tercahorarioiniciotarde { get; set; }
        public string tercahorariofimtarde { get; set; }
        public string tercahorarioinicionoite { get; set; }
        public string tercahorariofimnoite { get; set; }
        public string quartaatende { get; set; }
        public string quartahorarioiniciomanha { get; set; }
        public string quartahorariofimmanha { get; set; }
        public string quartahorarioiniciotarde { get; set; }
        public string quartahorariofimtarde { get; set; }
        public string quartahorarioinicionoite { get; set; }
        public string quartahorariofimnoite { get; set; }
        public string quintaatende { get; set; }
        public string quintahorarioiniciomanha { get; set; }
        public string quintahorariofimmanha { get; set; }
        public string quintahorarioiniciotarde { get; set; }
        public string quintahorariofimtarde { get; set; }
        public string quintahorarioinicionoite { get; set; }
        public string quintahorariofimnoite { get; set; }
        public string sextaatende { get; set; }
        public string sextahorarioiniciomanha { get; set; }
        public string sextahorariofimmanha { get; set; }
        public string sextahorarioiniciotarde { get; set; }
        public string sextahorariofimtarde { get; set; }
        public string sextahorarioinicionoite { get; set; }
        public string sextahorariofimnoite { get; set; }
        public string sabadoatende { get; set; }
        public string sabadohorarioiniciomanha { get; set; }
        public string sabadohorariofimmanha { get; set; }
        public string sabadohorarioiniciotarde { get; set; }
        public string sabadohorariofimtarde { get; set; }
        public string sabadohorarioinicionoite { get; set; }
        public string sabadohorariofimnoite { get; set; }
        public string mensagemindisponibilidade { get; set; }
        public string tipo { get; set; }
        public string positus { get; set; }
        public string positustoken { get; set; }
        public string positusmensagemrecorrente { get; set; }
        public string mensagemfila { get; set; }
        public string mensagemavaliacao { get; set; }
        public string nvoipusertoken { get; set; }
        public string numerowhatsapp { get; set; }
        public string numerowhatsapppais { get; set; }
        public string numerowhatsappsiglapais { get; set; }
        public string numerowhatsappdialcodepais { get; set; }
        public string disponibilizarcomosuporteparapostosautorizados { get; set; }
        public string canalpadraoconversadentroatendimento { get; set; }
        public string servicosqs { get; set; }
        public string dialog360 { get; set; }
        public string dialog360api_key { get; set; }
        public string dialog360app_id { get; set; }
        public string dialog360id { get; set; }
        public string dialog360channel { get; set; }
        public Nullable<int> tempoencerramentoautomaticobot { get; set; }
        public string mensagemencerramentoautomaticobot { get; set; }
        public string visualizacaorestritagrupos { get; set; }
        public string meta { get; set; }
        public string metaversaoapi { get; set; }
        public string metaaccesstoken { get; set; }
        public string metawabaid { get; set; }
        public string corwidget { get; set; }
        public string domingoencerrarconversaindisponibilidade { get; set; }
        public string segundaencerrarconversaindisponibilidade { get; set; }
        public string tercaencerrarconversaindisponibilidade { get; set; }
        public string quartaencerrarconversaindisponibilidade { get; set; }
        public string quintaencerrarconversaindisponibilidade { get; set; }
        public string sextaencerrarconversaindisponibilidade { get; set; }
        public string sabadoencerrarconversaindisponibilidade { get; set; }
        public string domingomensagemindisponibilidade { get; set; }
        public string segundamensagemindisponibilidade { get; set; }
        public string tercamensagemindisponibilidade { get; set; }
        public string quartamensagemindisponibilidade { get; set; }
        public string quintamensagemindisponibilidade { get; set; }
        public string sextamensagemindisponibilidade { get; set; }
        public string sabadomensagemindisponibilidade { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string finalidade { get; set; }
        public string permiteencerrarsemmensagemdeencerramento { get; set; }
        public Nullable<int> tempominutosbloqueionovaconversa { get; set; }
        public string webhook { get; set; }
        public string instagram { get; set; }
        public string instagramaccountname { get; set; }
        public string instagramversaoapi { get; set; }
        public string instagramaccesstoken { get; set; }
        public string resumopromptia { get; set; }
        public string mensagemautomaticaemespera { get; set; }
        public string emailsnotificacoes { get; set; }
        public string enviarconversaporemail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campanhas> Campanhas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamadas> Chamadas { get; set; }
        public virtual Chatbots Chatbots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsCanaisUsuarios> ChatsCanaisUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadesOrdensServicos> FinalidadesOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadesOrdensServicosGerais> FinalidadesOrdensServicosGerais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposCallCenter> GruposCallCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IASConsumoTokens> IASConsumoTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumerosWhatsAppSubFilasSQS> NumerosWhatsAppSubFilasSQS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesParametrosGatewayPagamento> OportunidadesParametrosGatewayPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametrosNegocios> ParametrosNegocios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesMeta> TemplatesMeta { get; set; }
    }
}
