//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OportunidadesProdutos()
        {
            this.Oportunidades = new HashSet<Oportunidades>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public Nullable<int> mesesvencimentogarantia { get; set; }
        public Nullable<int> mesesgarantiaestendida { get; set; }
        public decimal preco { get; set; }
        public string ativo { get; set; }
        public string obs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
    }
}
