//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesProdutosPacotesServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OportunidadesProdutosPacotesServicos()
        {
            this.OportunidadesProdutosPacotesServicosFamilias = new HashSet<OportunidadesProdutosPacotesServicosFamilias>();
            this.OportunidadesProdutosPacotesServicosProdutos = new HashSet<OportunidadesProdutosPacotesServicosProdutos>();
            this.OportunidadesProdutosPacotesServicosServicos = new HashSet<OportunidadesProdutosPacotesServicosServicos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesProdutosPacotesServicosFamilias> OportunidadesProdutosPacotesServicosFamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesProdutosPacotesServicosProdutos> OportunidadesProdutosPacotesServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesProdutosPacotesServicosServicos> OportunidadesProdutosPacotesServicosServicos { get; set; }
    }
}
