//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oportunidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oportunidades()
        {
            this.Atividades = new HashSet<Atividades>();
            this.CampanhasContatos = new HashSet<CampanhasContatos>();
            this.Chats = new HashSet<Chats>();
            this.OportunidadesAtualizacoesStatus = new HashSet<OportunidadesAtualizacoesStatus>();
            this.OportunidadesChecklists = new HashSet<OportunidadesChecklists>();
            this.OportunidadesDistribuicaoAutomatica = new HashSet<OportunidadesDistribuicaoAutomatica>();
            this.OportunidadesInteracoes = new HashSet<OportunidadesInteracoes>();
            this.OportunidadesTags = new HashSet<OportunidadesTags>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public string token { get; set; }
        public System.DateTime datageracao { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public Nullable<int> contatoid { get; set; }
        public Nullable<int> entidadeid { get; set; }
        public Nullable<int> produtoid { get; set; }
        public Nullable<int> oportunidadeprodutoid { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string status { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> paineloportunidadeid { get; set; }
        public string descricao { get; set; }
        public string linkpagamento { get; set; }
        public Nullable<decimal> valorproduto { get; set; }
        public Nullable<decimal> percenualtaxaplataforma { get; set; }
        public Nullable<decimal> valortaxaplataforma { get; set; }
        public Nullable<decimal> percentualtaxaadministradoracartao { get; set; }
        public Nullable<decimal> valortaxaadministradoracartao { get; set; }
        public Nullable<decimal> valoroutrasdespesas { get; set; }
        public Nullable<decimal> valorliquido { get; set; }
        public string transacaoidgatewaypagamento { get; set; }
        public string disponivelmodulonegocios { get; set; }
        public Nullable<System.DateTime> previsaoconclusao { get; set; }
        public Nullable<System.DateTime> dataconclusao { get; set; }
        public string conclusao { get; set; }
        public Nullable<int> origemoportunidadeid { get; set; }
        public Nullable<int> motivoperdaid { get; set; }
        public string obs { get; set; }
        public Nullable<int> usuarioidvendedor { get; set; }
        public string usuarionomevendedor { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividades> Atividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampanhasContatos> CampanhasContatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual MotivosPerdasOportunidades MotivosPerdasOportunidades { get; set; }
        public virtual OportunidadesOrigens OportunidadesOrigens { get; set; }
        public virtual OportunidadesProdutos OportunidadesProdutos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual PaineisOportunidades PaineisOportunidades { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesAtualizacoesStatus> OportunidadesAtualizacoesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesChecklists> OportunidadesChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesDistribuicaoAutomatica> OportunidadesDistribuicaoAutomatica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesInteracoes> OportunidadesInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesTags> OportunidadesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
