//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesParametrosGatewayPagamento
    {
        public int id { get; set; }
        public string intervalotransferencia { get; set; }
        public int diatransferencia { get; set; }
        public string recebedoridpagarme { get; set; }
        public decimal percentualrecebedor { get; set; }
        public string agencia { get; set; }
        public string agenciadv { get; set; }
        public string conta { get; set; }
        public string contadv { get; set; }
        public string codigobanco { get; set; }
        public string cpfcnpj { get; set; }
        public string nometitular { get; set; }
        public string contaidpagarme { get; set; }
        public int numeromaximoparcelas { get; set; }
        public Nullable<int> numeroid { get; set; }
    
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
    }
}
