//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesChecklists
    {
        public int id { get; set; }
        public int checklistitemid { get; set; }
        public int oportunidadeid { get; set; }
        public int statusid { get; set; }
        public string item { get; set; }
        public string detalheitem { get; set; }
        public string resposta { get; set; }
        public Nullable<decimal> respostanumber { get; set; }
        public string obs { get; set; }
        public string labelok { get; set; }
        public string labelnok { get; set; }
        public string opcoes { get; set; }
    
        public virtual Oportunidades Oportunidades { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
    }
}
