//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesAtualizacoesStatus
    {
        public int id { get; set; }
        public int oportunidadeid { get; set; }
        public Nullable<int> statusidanterior { get; set; }
        public Nullable<int> statusidatualizado { get; set; }
        public System.DateTime dataatualizacao { get; set; }
    
        public virtual Oportunidades Oportunidades { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
        public virtual StatusOportunidades StatusOportunidades1 { get; set; }
    }
}
