//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadesInteracoes
    {
        public int id { get; set; }
        public int oportunidadeid { get; set; }
        public System.DateTime datahora { get; set; }
        public string interacao { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public Nullable<int> fileid { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Oportunidades Oportunidades { get; set; }
    }
}
