//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosDefeitosConstatados
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public int ordemprodutoid { get; set; }
        public int defeitoconstatadoid { get; set; }
        public Nullable<decimal> valormaodeobra { get; set; }
    
        public virtual DefeitosConstatados DefeitosConstatados { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual OrdensServicosProdutos OrdensServicosProdutos { get; set; }
    }
}
