//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdensServicos()
        {
            this.AtendimentosOrdensServicos = new HashSet<AtendimentosOrdensServicos>();
            this.Atividades = new HashSet<Atividades>();
            this.AvaliacoesAtendimentos = new HashSet<AvaliacoesAtendimentos>();
            this.CamposPersonalizadosOrdensServicos = new HashSet<CamposPersonalizadosOrdensServicos>();
            this.ChatsOnlineUsersOrdensServicos = new HashSet<ChatsOnlineUsersOrdensServicos>();
            this.EnderecoProduto = new HashSet<EnderecoProduto>();
            this.Extratos = new HashSet<Extratos>();
            this.NaoConformidadesOrdensServicos = new HashSet<NaoConformidadesOrdensServicos>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OrdensServicos1 = new HashSet<OrdensServicos>();
            this.OrdensServicosAnexos = new HashSet<OrdensServicosAnexos>();
            this.OrdensServicosApontamentos = new HashSet<OrdensServicosApontamentos>();
            this.OrdensServicosAuditoria = new HashSet<OrdensServicosAuditoria>();
            this.OrdensServicosAuditoria1 = new HashSet<OrdensServicosAuditoria>();
            this.OrdensServicosAutorizacoes = new HashSet<OrdensServicosAutorizacoes>();
            this.OrdensServicosChecklists = new HashSet<OrdensServicosChecklists>();
            this.OrdensServicosChecks = new HashSet<OrdensServicosChecks>();
            this.OrdensServicosDadosExternos = new HashSet<OrdensServicosDadosExternos>();
            this.OrdensServicosDefeitosConstatados = new HashSet<OrdensServicosDefeitosConstatados>();
            this.OrdensServicosDefeitosReclamados = new HashSet<OrdensServicosDefeitosReclamados>();
            this.OrdensServicosEntidades = new HashSet<OrdensServicosEntidades>();
            this.OrdensServicosInteracoes = new HashSet<OrdensServicosInteracoes>();
            this.OrdensServicosPecas = new HashSet<OrdensServicosPecas>();
            this.OrdensServicosPostosAutorizadosAdicionais = new HashSet<OrdensServicosPostosAutorizadosAdicionais>();
            this.OrdensServicosServicosAdicionais = new HashSet<OrdensServicosServicosAdicionais>();
            this.OrdensServicosTags = new HashSet<OrdensServicosTags>();
            this.OrdensServicosTecnicosAdicionais = new HashSet<OrdensServicosTecnicosAdicionais>();
            this.OrdensServicosVeiculos = new HashSet<OrdensServicosVeiculos>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
            this.RastreamentoTecnicos = new HashSet<RastreamentoTecnicos>();
            this.Refurbished = new HashSet<Refurbished>();
            this.VisualizacaoConsultaPublicaLinks = new HashSet<VisualizacaoConsultaPublicaLinks>();
        }
    
        public int id { get; set; }
        public string numerosuaos { get; set; }
        public Nullable<int> ordemidorigem { get; set; }
        public Nullable<int> sequencia { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public string tipo { get; set; }
        public Nullable<int> finalidadeid { get; set; }
        public int postoid { get; set; }
        public Nullable<int> unidadeid { get; set; }
        public Nullable<int> postoidmaisproximo { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public System.DateTime dataabertura { get; set; }
        public Nullable<int> usuarioidabertura { get; set; }
        public string dispositivoabertura { get; set; }
        public string dispositivolancamento { get; set; }
        public Nullable<System.DateTime> dataconserto { get; set; }
        public Nullable<int> usuarioidconserto { get; set; }
        public Nullable<System.DateTime> datafechamento { get; set; }
        public Nullable<int> usuarioidfechamento { get; set; }
        public Nullable<System.DateTime> datacompra { get; set; }
        public string notafiscal { get; set; }
        public string garantiaexpirada { get; set; }
        public string defeitoreclamado { get; set; }
        public Nullable<int> defeitoreclamadoid { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public string acessorios { get; set; }
        public string obs { get; set; }
        public Nullable<int> notafiscalfileid { get; set; }
        public Nullable<int> fotoproduto1fileid { get; set; }
        public Nullable<int> fotoproduto2fileid { get; set; }
        public Nullable<int> fotoproduto3fileid { get; set; }
        public Nullable<int> fotoproduto4fileid { get; set; }
        public Nullable<int> aceiteconsumidorfileid { get; set; }
        public Nullable<int> assinaturaconsumidorfileid { get; set; }
        public string nomeassinatura { get; set; }
        public string status { get; set; }
        public string origem { get; set; }
        public string imprimeos { get; set; }
        public Nullable<System.DateTime> datacancelamento { get; set; }
        public Nullable<int> usuarioidcancelamento { get; set; }
        public Nullable<System.DateTime> dataproducao { get; set; }
        public string motivopagamentobloqueado { get; set; }
        public string usuariopapelabertura { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> dataagendamento { get; set; }
        public Nullable<int> fotoproduto5fileid { get; set; }
        public Nullable<int> fotoproduto6fileid { get; set; }
        public Nullable<int> fotoproduto7fileid { get; set; }
        public Nullable<int> fotoproduto8fileid { get; set; }
        public Nullable<int> statusordemservicoid { get; set; }
        public Nullable<int> usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public Nullable<int> slaid { get; set; }
        public Nullable<int> finalidadeordemgeralid { get; set; }
        public string char1 { get; set; }
        public string usuarionomeabertura { get; set; }
        public Nullable<System.DateTime> dataagendamentofim { get; set; }
        public string liberadoapp { get; set; }
        public string finalizadasemresolucao { get; set; }
        public Nullable<int> motivocancelamentoid { get; set; }
        public Nullable<int> assinaturacontatoid { get; set; }
        public string usuarionomefechamento { get; set; }
        public Nullable<decimal> dec1 { get; set; }
        public string liberadoposto { get; set; }
        public Nullable<decimal> distanciacalculada { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosOrdensServicos> AtendimentosOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atividades> Atividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacoesAtendimentos> AvaliacoesAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosOrdensServicos> CamposPersonalizadosOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsOnlineUsersOrdensServicos> ChatsOnlineUsersOrdensServicos { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual Contatos Contatos { get; set; }
        public virtual DefeitosReclamados DefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnderecoProduto> EnderecoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extratos> Extratos { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual Files Files2 { get; set; }
        public virtual Files Files3 { get; set; }
        public virtual Files Files4 { get; set; }
        public virtual Files Files5 { get; set; }
        public virtual Files Files6 { get; set; }
        public virtual Files Files7 { get; set; }
        public virtual Files Files8 { get; set; }
        public virtual Files Files9 { get; set; }
        public virtual Files Files10 { get; set; }
        public virtual FinalidadesOrdensServicos FinalidadesOrdensServicos { get; set; }
        public virtual FinalidadesOrdensServicosGerais FinalidadesOrdensServicosGerais { get; set; }
        public virtual MotivosCancelamentosOrdensServicos MotivosCancelamentosOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesOrdensServicos> NaoConformidadesOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos1 { get; set; }
        public virtual OrdensServicos OrdensServicos2 { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual PostosAutorizados PostosAutorizados1 { get; set; }
        public virtual PostosAutorizadosUnidades PostosAutorizadosUnidades { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual StatusOrdensServicos StatusOrdensServicos { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosAnexos> OrdensServicosAnexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosApontamentos> OrdensServicosApontamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosAuditoria> OrdensServicosAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosAuditoria> OrdensServicosAuditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosAutorizacoes> OrdensServicosAutorizacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosChecklists> OrdensServicosChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosChecks> OrdensServicosChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDadosExternos> OrdensServicosDadosExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosConstatados> OrdensServicosDefeitosConstatados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosReclamados> OrdensServicosDefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosEntidades> OrdensServicosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosInteracoes> OrdensServicosInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPecas> OrdensServicosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPostosAutorizadosAdicionais> OrdensServicosPostosAutorizadosAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosServicosAdicionais> OrdensServicosServicosAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosTags> OrdensServicosTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosTecnicosAdicionais> OrdensServicosTecnicosAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosVeiculos> OrdensServicosVeiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RastreamentoTecnicos> RastreamentoTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refurbished> Refurbished { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualizacaoConsultaPublicaLinks> VisualizacaoConsultaPublicaLinks { get; set; }
    }
}
