//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosAutorizacoes
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public string autorizacao { get; set; }
        public System.DateTime data { get; set; }
        public int usuarioidresponsavel { get; set; }
        public string usuarionomeresponsavel { get; set; }
        public string ativo { get; set; }
        public Nullable<System.DateTime> datarevogacao { get; set; }
        public Nullable<int> usuarioidrevogacao { get; set; }
        public string usuarionomerevogacao { get; set; }
    
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
