//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosChecklists
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public int ordemprodutoid { get; set; }
        public int checklistid { get; set; }
        public int ordemgrupo { get; set; }
        public string descricaogrupo { get; set; }
        public int ordemitem { get; set; }
        public string item { get; set; }
        public string detalheitem { get; set; }
        public string resposta { get; set; }
        public string obs { get; set; }
        public string labelok { get; set; }
        public string labelnok { get; set; }
        public Nullable<int> pontuacaook { get; set; }
        public Nullable<int> pontuacaonok { get; set; }
        public Nullable<int> foto1fileid { get; set; }
        public Nullable<int> foto2fileid { get; set; }
        public string obsgrupo { get; set; }
        public string tipoitem { get; set; }
        public string obrigatoriofotositem { get; set; }
        public string obrigatoriovideoitem { get; set; }
        public Nullable<int> video1fileid { get; set; }
        public Nullable<decimal> respostanumber { get; set; }
        public string opcoes { get; set; }
    
        public virtual Checklists Checklists { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual Files Files2 { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual OrdensServicosProdutos OrdensServicosProdutos { get; set; }
    }
}
