//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosApontamentos
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public Nullable<int> postoid { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public string tipo { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> fim { get; set; }
        public string latinicio { get; set; }
        public string lnginicio { get; set; }
        public string latfim { get; set; }
        public string lngfim { get; set; }
        public string relato { get; set; }
        public Nullable<int> assinaturaconsumidorfileid { get; set; }
        public Nullable<int> assinaturacontatoid { get; set; }
        public Nullable<int> ordemveiculoid { get; set; }
        public Nullable<int> kminicio { get; set; }
        public Nullable<int> kmfim { get; set; }
    
        public virtual Contatos Contatos { get; set; }
        public virtual Files Files { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
