//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosTecnicosAdicionais
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public int tecnicoid { get; set; }
    
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
