//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosAuditoria
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public Nullable<int> ordemidanterior { get; set; }
        public System.DateTime data { get; set; }
        public string tipo { get; set; }
        public string status { get; set; }
        public Nullable<int> usuarioidintervencao { get; set; }
        public string usuarionomeintervencao { get; set; }
        public Nullable<System.DateTime> dataintervencao { get; set; }
        public string obs { get; set; }
        public string retornapecasestoque { get; set; }
    
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual OrdensServicos OrdensServicos1 { get; set; }
    }
}
