//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdensServicosProdutos()
        {
            this.CamposPersonalizadosOrdensServicosProdutos = new HashSet<CamposPersonalizadosOrdensServicosProdutos>();
            this.MovtoEstoque = new HashSet<MovtoEstoque>();
            this.NaoConformidadesOrdensServicos = new HashSet<NaoConformidadesOrdensServicos>();
            this.OrdensServicosChecklists = new HashSet<OrdensServicosChecklists>();
            this.OrdensServicosDefeitosConstatados = new HashSet<OrdensServicosDefeitosConstatados>();
            this.OrdensServicosDefeitosReclamados = new HashSet<OrdensServicosDefeitosReclamados>();
            this.OrdensServicosPecas = new HashSet<OrdensServicosPecas>();
            this.OrdensServicosServicosAdicionais = new HashSet<OrdensServicosServicosAdicionais>();
        }
    
        public int id { get; set; }
        public int ordemid { get; set; }
        public Nullable<int> produtoid { get; set; }
        public Nullable<int> servicoid { get; set; }
        public string lote { get; set; }
        public Nullable<int> estruturaversionadacapaid { get; set; }
        public string versaohardware { get; set; }
        public string versaofirmware { get; set; }
        public string aparenciaproduto { get; set; }
        public string defeitoreclamado { get; set; }
        public Nullable<int> defeitoreclamadoid { get; set; }
        public Nullable<int> defeitoconstatadoid { get; set; }
        public decimal valorunitario { get; set; }
        public decimal valormaodeobraposto { get; set; }
        public Nullable<System.DateTime> datalancamento { get; set; }
        public string obs { get; set; }
        public string pecassolicitadassemcadastro { get; set; }
        public string status { get; set; }
        public string salvoulancamento { get; set; }
        public Nullable<int> fotoproduto1fileid { get; set; }
        public Nullable<int> fotoproduto2fileid { get; set; }
        public Nullable<int> fotoproduto3fileid { get; set; }
        public Nullable<int> fotoproduto4fileid { get; set; }
        public Nullable<int> refurbishedid { get; set; }
        public Nullable<int> horimetro { get; set; }
        public Nullable<int> horimetro2 { get; set; }
        public string relato { get; set; }
        public string estruturautilizada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosOrdensServicosProdutos> CamposPersonalizadosOrdensServicosProdutos { get; set; }
        public virtual DefeitosConstatados DefeitosConstatados { get; set; }
        public virtual DefeitosReclamados DefeitosReclamados { get; set; }
        public virtual EstruturasVersionadasCapa EstruturasVersionadasCapa { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual Files Files2 { get; set; }
        public virtual Files Files3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovtoEstoque> MovtoEstoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidadesOrdensServicos> NaoConformidadesOrdensServicos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosChecklists> OrdensServicosChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosConstatados> OrdensServicosDefeitosConstatados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosDefeitosReclamados> OrdensServicosDefeitosReclamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPecas> OrdensServicosPecas { get; set; }
        public virtual Refurbished Refurbished { get; set; }
        public virtual Servicos Servicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosServicosAdicionais> OrdensServicosServicosAdicionais { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
