//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosPecas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdensServicosPecas()
        {
            this.NotasFiscaisPendenciasDevolucaoPecas = new HashSet<NotasFiscaisPendenciasDevolucaoPecas>();
        }
    
        public int id { get; set; }
        public int ordemid { get; set; }
        public Nullable<int> ordemprodutoid { get; set; }
        public System.DateTime data { get; set; }
        public int pecaid { get; set; }
        public decimal quantidade { get; set; }
        public Nullable<int> pedidoid { get; set; }
        public Nullable<decimal> quantidadeutilizadaestoque { get; set; }
        public Nullable<decimal> quantidadepedido { get; set; }
        public Nullable<decimal> quantidadependentedevolucao { get; set; }
        public Nullable<decimal> quantidadependenteconferencia { get; set; }
        public string mensagemconferenciadevolucao { get; set; }
        public Nullable<int> defeitopecaid { get; set; }
        public string obs { get; set; }
        public Nullable<int> acaoreparoid { get; set; }
        public Nullable<int> pecapaiid { get; set; }
        public Nullable<decimal> quantidadedevolucaocancelada { get; set; }
    
        public virtual AcoesReparo AcoesReparo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPendenciasDevolucaoPecas> NotasFiscaisPendenciasDevolucaoPecas { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual OrdensServicosProdutos OrdensServicosProdutos { get; set; }
        public virtual Pecas Pecas { get; set; }
        public virtual PecasDefeitos PecasDefeitos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
