//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosChecks
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public string tipo { get; set; }
        public System.DateTime datahora { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string relato { get; set; }
        public Nullable<int> assinaturaconsumidorfileid { get; set; }
        public string nomeassinatura { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
