//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosEntidades
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public int entidadeid { get; set; }
        public string entidadedeslocamento { get; set; }
        public Nullable<int> entidadeenderecoid { get; set; }
        public string entidadeextrato { get; set; }
        public string entidadepedido { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        public virtual EntidadesEnderecosAdicionais EntidadesEnderecosAdicionais { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
    }
}
