//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosServicosAdicionais
    {
        public int id { get; set; }
        public int ordemid { get; set; }
        public int ordemprodutoid { get; set; }
        public int servicoadicionalid { get; set; }
        public decimal qtde { get; set; }
        public decimal valor { get; set; }
        public decimal total { get; set; }
        public string obs { get; set; }
        public Nullable<decimal> distanciacalculadaatweb { get; set; }
        public Nullable<int> comprovantefileid { get; set; }
        public Nullable<decimal> valoridentificadopelaia { get; set; }
        public string char1 { get; set; }
        public Nullable<int> usuarioidlancamento { get; set; }
        public string usuarionomelancamento { get; set; }
        public string usuariologinlancamento { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual OrdensServicosProdutos OrdensServicosProdutos { get; set; }
        public virtual ServicosAdicionais ServicosAdicionais { get; set; }
    }
}
