//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicosInteracoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdensServicosInteracoes()
        {
            this.OrdensServicosInteracoes1 = new HashSet<OrdensServicosInteracoes>();
            this.OrdensServicosInteracoesAuditoriaLeitura = new HashSet<OrdensServicosInteracoesAuditoriaLeitura>();
        }
    
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int usuarioidremetente { get; set; }
        public string remetente { get; set; }
        public string mensagem { get; set; }
        public string status { get; set; }
        public int ordemid { get; set; }
        public Nullable<int> interacaoidresposta { get; set; }
    
        public virtual OrdensServicos OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosInteracoes> OrdensServicosInteracoes1 { get; set; }
        public virtual OrdensServicosInteracoes OrdensServicosInteracoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosInteracoesAuditoriaLeitura> OrdensServicosInteracoesAuditoriaLeitura { get; set; }
    }
}
