//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaineisOportunidadesFluxosAtendimento
    {
        public int id { get; set; }
        public int paineloportunidadeid { get; set; }
        public int statusoportunidadeid { get; set; }
        public int fluxoatendimentoetapaid { get; set; }
    
        public virtual FluxosAtendimentoMessagingCenterEtapas FluxosAtendimentoMessagingCenterEtapas { get; set; }
        public virtual PaineisOportunidades PaineisOportunidades { get; set; }
        public virtual StatusOportunidades StatusOportunidades { get; set; }
    }
}
