//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaineisAtendimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaineisAtendimentos()
        {
            this.PaineisAtendimentosPadraoUsuarios = new HashSet<PaineisAtendimentosPadraoUsuarios>();
            this.PaineisAtendimentosStatusAtendimentos = new HashSet<PaineisAtendimentosStatusAtendimentos>();
        }
    
        public int id { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public string descricao { get; set; }
        public string ocultarcardsemstatusdefinido { get; set; }
        public string publico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisAtendimentosPadraoUsuarios> PaineisAtendimentosPadraoUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisAtendimentosStatusAtendimentos> PaineisAtendimentosStatusAtendimentos { get; set; }
    }
}
