//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaineisOportunidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaineisOportunidades()
        {
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OportunidadesDistribuicaoAutomatica = new HashSet<OportunidadesDistribuicaoAutomatica>();
            this.PaineisOportunidadesFluxosAtendimento = new HashSet<PaineisOportunidadesFluxosAtendimento>();
            this.PaineisOportunidadesEditores = new HashSet<PaineisOportunidadesEditores>();
            this.PaineisOportunidadesPadraoUsuarios = new HashSet<PaineisOportunidadesPadraoUsuarios>();
            this.PaineisOportunidadesStatusOportunidades = new HashSet<PaineisOportunidadesStatusOportunidades>();
            this.PaineisOportunidadesUsuarios = new HashSet<PaineisOportunidadesUsuarios>();
        }
    
        public int id { get; set; }
        public int usuarioid { get; set; }
        public string usuarionome { get; set; }
        public string descricao { get; set; }
        public string publico { get; set; }
        public string visualizacaorestritaresponsavel { get; set; }
        public string distribuicaoautomaticaoportunidades { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesDistribuicaoAutomatica> OportunidadesDistribuicaoAutomatica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesFluxosAtendimento> PaineisOportunidadesFluxosAtendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesEditores> PaineisOportunidadesEditores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesPadraoUsuarios> PaineisOportunidadesPadraoUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesStatusOportunidades> PaineisOportunidadesStatusOportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesUsuarios> PaineisOportunidadesUsuarios { get; set; }
    }
}
