//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaineisAtendimentosStatusOrdensServicos
    {
        public int id { get; set; }
        public int painelordemservicoid { get; set; }
        public int statusordemservicoid { get; set; }
        public int ordem { get; set; }
    
        public virtual PaineisOrdensServicos PaineisOrdensServicos { get; set; }
        public virtual StatusOrdensServicos StatusOrdensServicos { get; set; }
    }
}
