//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosLojaVirtual
    {
        public int id { get; set; }
        public Nullable<int> banner { get; set; }
        public string corfundo { get; set; }
        public string cortextosprincipais { get; set; }
        public string cortextobotoes { get; set; }
        public string corfundobotoes { get; set; }
        public Nullable<System.DateTime> ultimaatualizacao { get; set; }
    
        public virtual Files Files { get; set; }
    }
}
