//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosGlobais
    {
        public int id { get; set; }
        public Nullable<int> numeropedido { get; set; }
        public Nullable<int> numeroprotocolo { get; set; }
        public string arquivolayoutexportacaopedido { get; set; }
        public Nullable<decimal> limitequantidadepecaspedidogarantia { get; set; }
        public string rptextratofinanceirodetalhado { get; set; }
        public string rptordensservicoreprovadasauditoria { get; set; }
        public string rptextracaoordensservico { get; set; }
        public string smtp { get; set; }
        public Nullable<bool> smtpssl { get; set; }
        public Nullable<int> smtpporta { get; set; }
        public string pop { get; set; }
        public Nullable<bool> popssl { get; set; }
        public Nullable<int> popporta { get; set; }
        public Nullable<int> diasnotificacaoosaguardandoanalise { get; set; }
        public string gerarpedidosordensservicospara { get; set; }
        public string validarkitgarantia { get; set; }
        public string aberturaordemservicorefurbished { get; set; }
        public string lancamentoordemservicorefurbished { get; set; }
        public string naturezadevolucaopecas { get; set; }
        public string cfopdevolucaopecas { get; set; }
        public string obsdevolucaopecas { get; set; }
        public Nullable<int> slacallcenter { get; set; }
        public Nullable<int> mindiasaguardandoanalisedashboardposto { get; set; }
        public Nullable<int> maxdiasaguardandoanalisedashboardposto { get; set; }
        public Nullable<int> mindiasauditoriadashboardposto { get; set; }
        public Nullable<long> maxdiasauditoriadashboardposto { get; set; }
        public Nullable<int> mindiasaguardandopecasdashboardposto { get; set; }
        public Nullable<int> maxdiasaguardandopecasdashboardposto { get; set; }
        public Nullable<int> mindiasaguardandoconsertodashboardposto { get; set; }
        public Nullable<int> maxdiasaguardandoconsertodashboardposto { get; set; }
        public string periodoinicialordensservico { get; set; }
        public string periodoinicialatendimentos { get; set; }
        public string periodoinicialpedidos { get; set; }
        public string periodoinicialatividades { get; set; }
        public string privacidadeinteracaoatendimento { get; set; }
        public string fechamentoextratomensal { get; set; }
        public string ocultarextratospendentespostos { get; set; }
        public string gravalogintegracaoordemservico { get; set; }
        public Nullable<int> diasreaberturaatendimentomailmonitor { get; set; }
        public Nullable<int> mesesvisao360revendedor { get; set; }
        public string salvaarquivoschat { get; set; }
        public string sugerirpostomaisproximanaalteracao { get; set; }
        public string naobloquearpagamentoordemservicoporpendenciadevolucaopecas { get; set; }
        public Nullable<int> prazoresolucaoatendimento { get; set; }
        public Nullable<int> prazoadministrativoenvionovoprodutoatendimento { get; set; }
        public Nullable<decimal> aliquotapis { get; set; }
        public Nullable<decimal> aliquotacofins { get; set; }
        public string habilitaravaliacaoatendimentochat { get; set; }
        public string prefixoArquivoEstrutura { get; set; }
        public string prefixoArquivoEstruturaVersionada { get; set; }
        public string prefixoArquivoPecas { get; set; }
        public string prefixoArquivoTabelasPrecosPecas { get; set; }
        public string prefixoArquivoFamiliasProdutos { get; set; }
        public string prefixoArquivoProdutos { get; set; }
        public string prefixoArquivoPostosAutorizados { get; set; }
        public string prefixoArquivoConsumidores { get; set; }
        public string prefixoArquivoRevendedores { get; set; }
        public string LayoutEstrutura { get; set; }
        public string LayoutEstruturaVersionada { get; set; }
        public string LayoutEstruturaVersionadaCapa { get; set; }
        public string LayoutPecas { get; set; }
        public string LayoutTabelasPrecosPecas { get; set; }
        public string LayoutFamiliasProdutos { get; set; }
        public string LayoutProdutos { get; set; }
        public string LayoutPostosAutorizados { get; set; }
        public string LayoutConsumidores { get; set; }
        public string LayoutRevendedores { get; set; }
        public string gravalogwebhookmessagingcenter { get; set; }
        public string prioridadelocalizacaomostrarmapaaplicativo { get; set; }
        public string mensagemnotificacaoaberturamailmonitor { get; set; }
        public string mensagemnotificacaoatualizacaomailmonitor { get; set; }
        public string imap { get; set; }
        public Nullable<bool> imapssl { get; set; }
        public Nullable<int> imapporta { get; set; }
        public string office365_oauth_clientId { get; set; }
        public string office365_oauth_tenantId { get; set; }
        public string office365_oauth_secretValue { get; set; }
        public Nullable<int> gerarpedidosordensservicosparatipoentidadeid { get; set; }
        public string gerarextratospara { get; set; }
        public string obrigatoriofinalidadeatividade { get; set; }
        public string clientemail { get; set; }
        public Nullable<decimal> percentualtoleranciadivergenciakm { get; set; }
        public string ocultarnumeroidentificacaocadastroentidade { get; set; }
        public string mensagemnaoreaberturaatendimentomailmonitor { get; set; }
        public string obrigatorioanexardanfedevolucaoobrigatoriapecas { get; set; }
        public string naoenviaremailpostoemdescredenciamento { get; set; }
        public Nullable<int> diasparaemissaodenotafiscal { get; set; }
    
        public virtual TiposEntidades TiposEntidades { get; set; }
    }
}
