//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PecasAdicionais
    {
        public int id { get; set; }
        public int pecaid { get; set; }
        public int pecaadicionalid { get; set; }
        public decimal quantidade { get; set; }
        public Nullable<System.DateTime> dataproducaoinicial { get; set; }
        public Nullable<System.DateTime> dataproducaofinal { get; set; }
        public string obs { get; set; }
        public string ativo { get; set; }
    
        public virtual Pecas Pecas { get; set; }
        public virtual Pecas Pecas1 { get; set; }
    }
}
