//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pecas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pecas()
        {
            this.Carrinho = new HashSet<Carrinho>();
            this.CatalogosConjuntosPecas = new HashSet<CatalogosConjuntosPecas>();
            this.DePara = new HashSet<DePara>();
            this.DePara1 = new HashSet<DePara>();
            this.EstoquePosto = new HashSet<EstoquePosto>();
            this.Estruturas = new HashSet<Estruturas>();
            this.EstruturasVersionadas = new HashSet<EstruturasVersionadas>();
            this.MovtoEstoque = new HashSet<MovtoEstoque>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.NotasFiscaisPecas = new HashSet<NotasFiscaisPecas>();
            this.OrdensServicosPecas = new HashSet<OrdensServicosPecas>();
            this.PecasAdicionais = new HashSet<PecasAdicionais>();
            this.PecasAdicionais1 = new HashSet<PecasAdicionais>();
            this.PecasDefeitos = new HashSet<PecasDefeitos>();
            this.PedidosPecas = new HashSet<PedidosPecas>();
            this.TabelasPrecosPecas = new HashSet<TabelasPrecosPecas>();
        }
    
        public int id { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public string origem { get; set; }
        public decimal ipi { get; set; }
        public string unidade { get; set; }
        public Nullable<decimal> pesoliquido { get; set; }
        public string classificacaofiscal { get; set; }
        public string multiplo { get; set; }
        public Nullable<int> mesesgarantiadiferenciada { get; set; }
        public string itemaparencia { get; set; }
        public string bloqueadogarantia { get; set; }
        public string bloqueadovenda { get; set; }
        public string acessorio { get; set; }
        public string pecacritica { get; set; }
        public string produtoacabado { get; set; }
        public string ativo { get; set; }
        public byte[] foto { get; set; }
        public string destaquelojavirtual { get; set; }
        public string char1 { get; set; }
        public string devolucaoobrigatoria { get; set; }
        public Nullable<decimal> pesobruto { get; set; }
        public Nullable<int> familiapecaid { get; set; }
        public Nullable<System.DateTime> devolucaoobrigatoriadataproducaoinicial { get; set; }
        public Nullable<System.DateTime> devolucaoobrigatoriadataproducaofinal { get; set; }
        public string devolucaoobrigatoriaestados { get; set; }
        public string char2 { get; set; }
        public string devolucaoobrigatoriadefeitosconstatados { get; set; }
        public string devolucaoobrigatoriadefeitospecas { get; set; }
        public Nullable<decimal> largura { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> comprimento { get; set; }
        public string descricaocomercial { get; set; }
        public string especificacoestecnicas { get; set; }
        public Nullable<int> foto1 { get; set; }
        public Nullable<int> foto2 { get; set; }
        public Nullable<int> foto3 { get; set; }
        public Nullable<int> foto4 { get; set; }
        public Nullable<int> foto5 { get; set; }
        public string origemcadastro { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public string descricao_normalizado { get; set; }
        public string descricaocomercial_normalizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosConjuntosPecas> CatalogosConjuntosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DePara> DePara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DePara> DePara1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstoquePosto> EstoquePosto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estruturas> Estruturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstruturasVersionadas> EstruturasVersionadas { get; set; }
        public virtual FamiliasPecas FamiliasPecas { get; set; }
        public virtual Files Files { get; set; }
        public virtual Files Files1 { get; set; }
        public virtual Files Files2 { get; set; }
        public virtual Files Files3 { get; set; }
        public virtual Files Files4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovtoEstoque> MovtoEstoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPecas> NotasFiscaisPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPecas> OrdensServicosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PecasAdicionais> PecasAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PecasAdicionais> PecasAdicionais1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PecasDefeitos> PecasDefeitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosPecas> PedidosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelasPrecosPecas> TabelasPrecosPecas { get; set; }
    }
}
