//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.CamposPersonalizadosPedidos = new HashSet<CamposPersonalizadosPedidos>();
            this.JobItem = new HashSet<JobItem>();
            this.MovtoEstoque = new HashSet<MovtoEstoque>();
            this.NotasFiscais = new HashSet<NotasFiscais>();
            this.OrdensServicosPecas = new HashSet<OrdensServicosPecas>();
            this.Pedidos1 = new HashSet<Pedidos>();
            this.PedidosCondicoesEspeciais = new HashSet<PedidosCondicoesEspeciais>();
            this.PedidosInteracoes = new HashSet<PedidosInteracoes>();
            this.PedidosPecas = new HashSet<PedidosPecas>();
            this.PedidosProdutos = new HashSet<PedidosProdutos>();
            this.VisualizacaoConsultaPublicaLinks = new HashSet<VisualizacaoConsultaPublicaLinks>();
        }
    
        public int id { get; set; }
        public int numeropedido { get; set; }
        public System.DateTime data { get; set; }
        public string notafiscal { get; set; }
        public Nullable<System.DateTime> datafaturamento { get; set; }
        public Nullable<int> postoid { get; set; }
        public Nullable<int> consumidorid { get; set; }
        public string tipopedido { get; set; }
        public string tipofrete { get; set; }
        public string status { get; set; }
        public Nullable<int> condicaopagamentoid { get; set; }
        public Nullable<int> tabelaprecoid { get; set; }
        public decimal percentualdesconto { get; set; }
        public decimal valordesconto { get; set; }
        public decimal total { get; set; }
        public string obs { get; set; }
        public string codigoenvio { get; set; }
        public string numeropedidofabricante { get; set; }
        public Nullable<int> revendedorid { get; set; }
        public Nullable<decimal> valorfrete { get; set; }
        public Nullable<int> prazoentregadias { get; set; }
        public string transportador { get; set; }
        public string codigoerptransportador { get; set; }
        public string char1 { get; set; }
        public Nullable<decimal> percentualacrescimo { get; set; }
        public Nullable<decimal> valoracrescimo { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public Nullable<int> postoiddistribuidor { get; set; }
        public Nullable<int> representanteid { get; set; }
        public Nullable<int> tabelafreteid { get; set; }
        public Nullable<int> cupomdescontoid { get; set; }
        public string char2 { get; set; }
        public Nullable<int> statuspedidoid { get; set; }
        public Nullable<int> tipopedidoid { get; set; }
        public Nullable<int> transportadoraid { get; set; }
        public string mensagemfrete { get; set; }
        public Nullable<decimal> dec1 { get; set; }
        public Nullable<decimal> valorfretehidden { get; set; }
        public Nullable<int> entidadeid { get; set; }
        public Nullable<decimal> percentualdescontopostoautorizado { get; set; }
        public Nullable<decimal> percentualdescontocondicaopagamento { get; set; }
        public Nullable<decimal> percentualdescontoadicional { get; set; }
        public Nullable<decimal> valormaodeobraprevisto { get; set; }
        public Nullable<decimal> valordeslocamentoprevisto { get; set; }
        public string numeropedidoexterno { get; set; }
        public string origempedidoexterno { get; set; }
        public string urlrastreio { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public string prioridade { get; set; }
        public string char3 { get; set; }
        public string pedidoprogramado { get; set; }
        public Nullable<System.DateTime> dataprevistaentrega { get; set; }
        public Nullable<int> oportunidadeid { get; set; }
        public string numeropedidoparceiro { get; set; }
        public Nullable<System.DateTime> validadeorcamento { get; set; }
        public Nullable<int> transportadoraidredespacho { get; set; }
        public Nullable<int> naturezaoperacaoid { get; set; }
        public Nullable<int> representanteidadicional { get; set; }
        public Nullable<decimal> percentualcomissaorepresentante { get; set; }
        public Nullable<decimal> percentualcomissaorepresentanteadicional { get; set; }
        public Nullable<decimal> totalimpostos { get; set; }
        public string numeroorcamentofabricante { get; set; }
        public Nullable<System.DateTime> dataintegracaoorcamento { get; set; }
        public Nullable<System.DateTime> dataintegracaopedido { get; set; }
        public Nullable<int> entidadeenderecoid { get; set; }
        public string invoice { get; set; }
        public Nullable<int> usuarioidvendedor { get; set; }
        public string usuarionomevendedor { get; set; }
        public Nullable<int> pedidoidorigem { get; set; }
        public Nullable<int> sequencia { get; set; }
        public Nullable<int> assinaturafileid { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamposPersonalizadosPedidos> CamposPersonalizadosPedidos { get; set; }
        public virtual CondicoesPagamento CondicoesPagamento { get; set; }
        public virtual Consumidores Consumidores { get; set; }
        public virtual CuponsDesconto CuponsDesconto { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual EntidadesEnderecosAdicionais EntidadesEnderecosAdicionais { get; set; }
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobItem> JobItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovtoEstoque> MovtoEstoque { get; set; }
        public virtual NaturezaOperacao NaturezaOperacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscais> NotasFiscais { get; set; }
        public virtual Oportunidades Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPecas> OrdensServicosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
        public virtual Pedidos Pedidos2 { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual PostosAutorizados PostosAutorizados1 { get; set; }
        public virtual Representantes Representantes { get; set; }
        public virtual Representantes Representantes1 { get; set; }
        public virtual Revendedores Revendedores { get; set; }
        public virtual StatusPedidos StatusPedidos { get; set; }
        public virtual TabelasFretes TabelasFretes { get; set; }
        public virtual TabelasPrecos TabelasPrecos { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
        public virtual TiposPedidos TiposPedidos { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
        public virtual Transportadoras Transportadoras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosCondicoesEspeciais> PedidosCondicoesEspeciais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosInteracoes> PedidosInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosPecas> PedidosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProdutos> PedidosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualizacaoConsultaPublicaLinks> VisualizacaoConsultaPublicaLinks { get; set; }
    }
}
