//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosProdutos
    {
        public int id { get; set; }
        public int pedidoid { get; set; }
        public int produtoid { get; set; }
        public decimal quantidade { get; set; }
        public Nullable<decimal> precotabela { get; set; }
        public decimal valorunitario { get; set; }
        public Nullable<decimal> percentualicms { get; set; }
        public Nullable<decimal> valoricms { get; set; }
        public Nullable<decimal> percentualipi { get; set; }
        public Nullable<decimal> valoripi { get; set; }
        public Nullable<decimal> percentualpis { get; set; }
        public Nullable<decimal> valorpis { get; set; }
        public Nullable<decimal> percentualcofins { get; set; }
        public Nullable<decimal> valorcofins { get; set; }
        public Nullable<decimal> percentualiss { get; set; }
        public Nullable<decimal> valoriss { get; set; }
        public decimal valortotal { get; set; }
        public string obs { get; set; }
        public string char1 { get; set; }
        public string char2 { get; set; }
        public Nullable<decimal> dec1 { get; set; }
        public Nullable<System.DateTime> dataprevistaentrega { get; set; }
        public Nullable<decimal> percentualdesconto { get; set; }
        public Nullable<decimal> percentualicmsst { get; set; }
        public Nullable<decimal> valoricmsst { get; set; }
        public string classificacaofiscal { get; set; }
        public string cfop { get; set; }
        public Nullable<decimal> pesoliquido { get; set; }
        public Nullable<decimal> pesobruto { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
