//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosCondicoesEspeciais
    {
        public int id { get; set; }
        public int pedidoid { get; set; }
        public string tipovencimento { get; set; }
        public Nullable<System.DateTime> datavencimento { get; set; }
        public Nullable<int> diasvencimento { get; set; }
        public Nullable<decimal> percentualpagamento { get; set; }
        public Nullable<decimal> valorparcela { get; set; }
        public string obs { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
