//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostosAutorizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostosAutorizados()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.Carrinho = new HashSet<Carrinho>();
            this.Chats = new HashSet<Chats>();
            this.ComunicadosPostosAutorizados = new HashSet<ComunicadosPostosAutorizados>();
            this.Contatos = new HashSet<Contatos>();
            this.EstoquePosto = new HashSet<EstoquePosto>();
            this.ExcessoesMaoDeObra = new HashSet<ExcessoesMaoDeObra>();
            this.ExtratosLotes = new HashSet<ExtratosLotes>();
            this.JobItem = new HashSet<JobItem>();
            this.MovtoEstoque = new HashSet<MovtoEstoque>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.OrdensServicos1 = new HashSet<OrdensServicos>();
            this.OrdensServicosApontamentos = new HashSet<OrdensServicosApontamentos>();
            this.OrdensServicosPostosAutorizadosAdicionais = new HashSet<OrdensServicosPostosAutorizadosAdicionais>();
            this.Pedidos = new HashSet<Pedidos>();
            this.Pedidos1 = new HashSet<Pedidos>();
            this.PostosAutorizados1 = new HashSet<PostosAutorizados>();
            this.PostosAutorizadosAnexos = new HashSet<PostosAutorizadosAnexos>();
            this.PostosAutorizadosCidadesAtendidas = new HashSet<PostosAutorizadosCidadesAtendidas>();
            this.PostosAutorizadosComentarios = new HashSet<PostosAutorizadosComentarios>();
            this.PostosAutorizadosFinalidadesOrdensServicos = new HashSet<PostosAutorizadosFinalidadesOrdensServicos>();
            this.PostosAutorizadosFinalidadesOrdensServicosGerais = new HashSet<PostosAutorizadosFinalidadesOrdensServicosGerais>();
            this.PostosAutorizadosLinhas = new HashSet<PostosAutorizadosLinhas>();
            this.PostosAutorizadosTabelasPrecosVenda = new HashSet<PostosAutorizadosTabelasPrecosVenda>();
            this.PostosAutorizadosUnidades = new HashSet<PostosAutorizadosUnidades>();
            this.PostosAutorizadosUsuarios = new HashSet<PostosAutorizadosUsuarios>();
            this.RastreamentoTecnicos = new HashSet<RastreamentoTecnicos>();
            this.Tecnicos = new HashSet<Tecnicos>();
        }
    
        public int id { get; set; }
        public string cnpj { get; set; }
        public string razaosocial { get; set; }
        public string nomefantasia { get; set; }
        public string inscricaoestadual { get; set; }
        public string telefone { get; set; }
        public string contato { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string email { get; set; }
        public int tipopostoid { get; set; }
        public int tabelaprecoid { get; set; }
        public decimal percentualdesconto { get; set; }
        public string regiaosuframa { get; set; }
        public string itemaparencia { get; set; }
        public string obs { get; set; }
        public string digitapedidofaturado { get; set; }
        public string digitapedidogarantia { get; set; }
        public string digitaos { get; set; }
        public string login { get; set; }
        public string status { get; set; }
        public string referencia { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public string postoexclusivo { get; set; }
        public string postocritico { get; set; }
        public Nullable<System.DateTime> datainiciodescredenciamento { get; set; }
        public string telefone2 { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string contacorrente { get; set; }
        public Nullable<decimal> valorkm { get; set; }
        public Nullable<int> diaressuprimento1 { get; set; }
        public Nullable<int> diaressuprimento2 { get; set; }
        public string digitaosrevendedor { get; set; }
        public Nullable<int> tabelaprecovendaid { get; set; }
        public string diasgeracaopedidogarantia { get; set; }
        public string rastreartecnicos { get; set; }
        public string pais { get; set; }
        public Nullable<decimal> percentualicms { get; set; }
        public Nullable<int> postoiddistribuidor { get; set; }
        public string telefone3 { get; set; }
        public string tipoatendimento { get; set; }
        public Nullable<int> representanteid { get; set; }
        public string ocultarsugestaoordemservico { get; set; }
        public string ocultarsugestaoatendimento { get; set; }
        public string telefonepais { get; set; }
        public string telefonesiglapais { get; set; }
        public string telefonedialcodepais { get; set; }
        public string telefone2pais { get; set; }
        public string telefone2siglapais { get; set; }
        public string telefone2dialcodepais { get; set; }
        public string telefone3pais { get; set; }
        public string telefone3siglapais { get; set; }
        public string telefone3dialcodepais { get; set; }
        public string tipofechamentoextrato { get; set; }
        public Nullable<int> periodofechamentoextrato { get; set; }
        public Nullable<int> qtdeosfechamentoextrato { get; set; }
        public Nullable<decimal> valorfechamentoextrato { get; set; }
        public Nullable<System.DateTime> ultimoacesso { get; set; }
        public string dispositivoultimoacesso { get; set; }
        public Nullable<System.DateTime> dataassinaturacontrato { get; set; }
        public Nullable<System.DateTime> dataatualizacaocontrato { get; set; }
        public Nullable<System.DateTime> dataultimofechamentoextrato { get; set; }
        public Nullable<decimal> dec1 { get; set; }
        public string telefonenotificacao { get; set; }
        public string telefonenotificacaopais { get; set; }
        public string telefonenotificacaosiglapais { get; set; }
        public string telefonenotificacaodialcodepais { get; set; }
        public Nullable<decimal> valorhora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosPostosAutorizados> ComunicadosPostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatos> Contatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstoquePosto> EstoquePosto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcessoesMaoDeObra> ExcessoesMaoDeObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtratosLotes> ExtratosLotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobItem> JobItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovtoEstoque> MovtoEstoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosApontamentos> OrdensServicosApontamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosPostosAutorizadosAdicionais> OrdensServicosPostosAutorizadosAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizados> PostosAutorizados1 { get; set; }
        public virtual PostosAutorizados PostosAutorizados2 { get; set; }
        public virtual Representantes Representantes { get; set; }
        public virtual TabelasPrecos TabelasPrecos { get; set; }
        public virtual TabelasPrecos TabelasPrecos1 { get; set; }
        public virtual TiposPostosAutorizados TiposPostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosAnexos> PostosAutorizadosAnexos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosCidadesAtendidas> PostosAutorizadosCidadesAtendidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosComentarios> PostosAutorizadosComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosFinalidadesOrdensServicos> PostosAutorizadosFinalidadesOrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosFinalidadesOrdensServicosGerais> PostosAutorizadosFinalidadesOrdensServicosGerais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosLinhas> PostosAutorizadosLinhas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosTabelasPrecosVenda> PostosAutorizadosTabelasPrecosVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosUnidades> PostosAutorizadosUnidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosUsuarios> PostosAutorizadosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RastreamentoTecnicos> RastreamentoTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tecnicos> Tecnicos { get; set; }
    }
}
