//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostosAutorizadosCidadesAtendidas
    {
        public int id { get; set; }
        public int postoid { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string cidadeorigem { get; set; }
        public string regiao { get; set; }
    
        public virtual PostosAutorizados PostosAutorizados { get; set; }
    }
}
