//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostosAutorizadosLinhas
    {
        public int id { get; set; }
        public int postoid { get; set; }
        public int linhaid { get; set; }
        public string atende { get; set; }
    
        public virtual LinhasProdutos LinhasProdutos { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
    }
}
