//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosSimilares
    {
        public int id { get; set; }
        public int produtoid { get; set; }
        public int produtosimilarid { get; set; }
        public string obs { get; set; }
        public string ativo { get; set; }
    
        public virtual Produtos Produtos { get; set; }
        public virtual Produtos Produtos1 { get; set; }
    }
}
