//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosConsumidores
    {
        public int id { get; set; }
        public int produtoid { get; set; }
        public int consumidorid { get; set; }
        public Nullable<int> estruturaversionadacapaid { get; set; }
        public Nullable<System.DateTime> datacompra { get; set; }
        public Nullable<int> notafiscalfileid { get; set; }
        public string loteserie { get; set; }
        public string notafiscal { get; set; }
        public string transportadora { get; set; }
        public string obs { get; set; }
        public string char1 { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<decimal> valortotal { get; set; }
    
        public virtual Consumidores Consumidores { get; set; }
        public virtual EstruturasVersionadasCapa EstruturasVersionadasCapa { get; set; }
        public virtual Files Files { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
