//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.ArvoreDiagnosticosProdutos = new HashSet<ArvoreDiagnosticosProdutos>();
            this.Atendimentos = new HashSet<Atendimentos>();
            this.AtendimentosProdutos = new HashSet<AtendimentosProdutos>();
            this.CatalogosProdutos = new HashSet<CatalogosProdutos>();
            this.Chats = new HashSet<Chats>();
            this.ChecklistsProdutos = new HashSet<ChecklistsProdutos>();
            this.ComunicadosProdutos = new HashSet<ComunicadosProdutos>();
            this.DocumentosProdutos = new HashSet<DocumentosProdutos>();
            this.Estruturas = new HashSet<Estruturas>();
            this.EstruturasVersionadasCapa = new HashSet<EstruturasVersionadasCapa>();
            this.ExcessoesMaoDeObra = new HashSet<ExcessoesMaoDeObra>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.NotasFiscaisProdutos = new HashSet<NotasFiscaisProdutos>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
            this.PedidosProdutos = new HashSet<PedidosProdutos>();
            this.ProdutosConsumidores = new HashSet<ProdutosConsumidores>();
            this.ProdutosSimilares = new HashSet<ProdutosSimilares>();
            this.ProdutosSimilares1 = new HashSet<ProdutosSimilares>();
            this.ReferenciasProdutosEntidades = new HashSet<ReferenciasProdutosEntidades>();
            this.Seg_ItensProdutos = new HashSet<Seg_ItensProdutos>();
            this.ServicosAdicionaisProdutosRestritos = new HashSet<ServicosAdicionaisProdutosRestritos>();
            this.TabelasPrecosProdutos = new HashSet<TabelasPrecosProdutos>();
        }
    
        public int id { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public int mesesgarantia { get; set; }
        public decimal valormaodeobraposto { get; set; }
        public int linhaid { get; set; }
        public int familiaid { get; set; }
        public string origem { get; set; }
        public string voltagem { get; set; }
        public string statusrede { get; set; }
        public string numeroserieobrigatorio { get; set; }
        public string produtoprincipal { get; set; }
        public string trocaobrigatoria { get; set; }
        public byte[] foto { get; set; }
        public string versaohardwareobrigatorio { get; set; }
        public string versaofirmwareobrigatorio { get; set; }
        public string modelo { get; set; }
        public Nullable<decimal> pesoliquido { get; set; }
        public Nullable<decimal> pesobruto { get; set; }
        public string desconsiderarestruturapecas { get; set; }
        public Nullable<decimal> dec1 { get; set; }
        public string informarhorimetro { get; set; }
        public string informarhorimetro2 { get; set; }
        public string origemcadastro { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public string referenciafornecedor { get; set; }
        public string classificacaofiscal { get; set; }
        public string unidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArvoreDiagnosticosProdutos> ArvoreDiagnosticosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosProdutos> AtendimentosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogosProdutos> CatalogosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsProdutos> ChecklistsProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadosProdutos> ComunicadosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosProdutos> DocumentosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estruturas> Estruturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstruturasVersionadasCapa> EstruturasVersionadasCapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcessoesMaoDeObra> ExcessoesMaoDeObra { get; set; }
        public virtual FamiliasProdutos FamiliasProdutos { get; set; }
        public virtual LinhasProdutos LinhasProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisProdutos> NotasFiscaisProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProdutos> PedidosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosConsumidores> ProdutosConsumidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosSimilares> ProdutosSimilares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosSimilares> ProdutosSimilares1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciasProdutosEntidades> ReferenciasProdutosEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_ItensProdutos> Seg_ItensProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosAdicionaisProdutosRestritos> ServicosAdicionaisProdutosRestritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelasPrecosProdutos> TabelasPrecosProdutos { get; set; }
    }
}
