//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RastreamentoTecnicos
    {
        public int id { get; set; }
        public Nullable<int> tecnicoid { get; set; }
        public Nullable<int> postoid { get; set; }
        public System.DateTime datahora { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<decimal> velocidade { get; set; }
        public Nullable<decimal> precisao { get; set; }
        public string checkin { get; set; }
        public Nullable<int> ordemid { get; set; }
    
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual PostosAutorizados PostosAutorizados { get; set; }
        public virtual Tecnicos Tecnicos { get; set; }
    }
}
