//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revendedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revendedores()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.Chats = new HashSet<Chats>();
            this.Contatos = new HashSet<Contatos>();
            this.EstruturasVersionadasCapa = new HashSet<EstruturasVersionadasCapa>();
            this.NaoConformidades = new HashSet<NaoConformidades>();
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.Pedidos = new HashSet<Pedidos>();
            this.RevendedoresComentarios = new HashSet<RevendedoresComentarios>();
        }
    
        public int id { get; set; }
        public string cnpj { get; set; }
        public string razaosocial { get; set; }
        public string inscricaoestadual { get; set; }
        public string telefone { get; set; }
        public string contato { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public string referencia { get; set; }
        public string nomefantasia { get; set; }
        public string telefone2 { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string contacorrente { get; set; }
        public Nullable<int> representanteid { get; set; }
        public string pais { get; set; }
        public string telefone3 { get; set; }
        public Nullable<int> mesesgarantia { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<decimal> percentualicms { get; set; }
        public string telefonepais { get; set; }
        public string telefonesiglapais { get; set; }
        public string telefonedialcodepais { get; set; }
        public string telefone2pais { get; set; }
        public string telefone2siglapais { get; set; }
        public string telefone2dialcodepais { get; set; }
        public string telefone3pais { get; set; }
        public string telefone3siglapais { get; set; }
        public string telefone3dialcodepais { get; set; }
        public string obsvisao360 { get; set; }
        public string razaosocial_normalizado { get; set; }
        public string nomefantasia_normalizado { get; set; }
        public string cidade_normalizado { get; set; }
        public Nullable<long> telefonenumber { get; set; }
        public Nullable<long> telefone2number { get; set; }
        public Nullable<long> telefone3number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatos> Contatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstruturasVersionadasCapa> EstruturasVersionadasCapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaoConformidades> NaoConformidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual Representantes Representantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevendedoresComentarios> RevendedoresComentarios { get; set; }
    }
}
