//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_Apolices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seg_Apolices()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.Seg_Coberturas = new HashSet<Seg_Coberturas>();
            this.Seg_ItensProdutos = new HashSet<Seg_ItensProdutos>();
            this.Seg_Pagamentos = new HashSet<Seg_Pagamentos>();
            this.Seg_Segurados = new HashSet<Seg_Segurados>();
        }
    
        public int id { get; set; }
        public System.DateTime datacriacao { get; set; }
        public string contrato { get; set; }
        public string apolice { get; set; }
        public string cnaedescricao { get; set; }
        public System.DateTime datainiciocontrato { get; set; }
        public System.DateTime datafinalcontrato { get; set; }
        public System.DateTime datainiciovigencia { get; set; }
        public System.DateTime datafinalvigencia { get; set; }
        public Nullable<System.DateTime> dataaverbacaoprevista { get; set; }
        public Nullable<System.DateTime> dataassinatura { get; set; }
        public Nullable<System.DateTime> dataproximovencimento { get; set; }
        public Nullable<System.DateTime> datalimitemovimento { get; set; }
        public Nullable<System.DateTime> datacadastrofatura { get; set; }
        public string situacao { get; set; }
        public string char1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_Coberturas> Seg_Coberturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_ItensProdutos> Seg_ItensProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_Pagamentos> Seg_Pagamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_Segurados> Seg_Segurados { get; set; }
    }
}
