//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_Pagamentos
    {
        public int id { get; set; }
        public int apoliceid { get; set; }
        public string referencia { get; set; }
        public string nossonum { get; set; }
        public string parcela { get; set; }
        public Nullable<System.DateTime> vencimento { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string situacao { get; set; }
        public string formapagamento { get; set; }
    
        public virtual Seg_Apolices Seg_Apolices { get; set; }
    }
}
