//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_Segurados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seg_Segurados()
        {
            this.Seg_Beneficiarios = new HashSet<Seg_Beneficiarios>();
        }
    
        public int id { get; set; }
        public int apoliceid { get; set; }
        public string referencia { get; set; }
        public string cpf { get; set; }
        public string rginscricaoestadual { get; set; }
        public string orgaoemissordocumento { get; set; }
        public Nullable<System.DateTime> dataemissaodocumento { get; set; }
        public string nome { get; set; }
        public string nomesocial { get; set; }
        public Nullable<System.DateTime> datanascimento { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public string telefoneresidencial { get; set; }
        public string telefonecomercial { get; set; }
        public string telefonecelular { get; set; }
        public string telefonesms { get; set; }
    
        public virtual Seg_Apolices Seg_Apolices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seg_Beneficiarios> Seg_Beneficiarios { get; set; }
    }
}
