//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_Coberturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seg_Coberturas()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
        }
    
        public int id { get; set; }
        public int apoliceid { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> capital { get; set; }
        public Nullable<decimal> premioliquido { get; set; }
        public Nullable<decimal> premiocia { get; set; }
        public Nullable<decimal> premiobruto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        public virtual Seg_Apolices Seg_Apolices { get; set; }
    }
}
