//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_Beneficiarios
    {
        public int id { get; set; }
        public Nullable<int> seguradoid { get; set; }
        public string nome { get; set; }
        public string parentesco { get; set; }
        public Nullable<decimal> percentual { get; set; }
    
        public virtual Seg_Segurados Seg_Segurados { get; set; }
    }
}
