//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seg_ItensProdutos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seg_ItensProdutos()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
        }
    
        public int id { get; set; }
        public int apoliceid { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> datacadastro { get; set; }
        public Nullable<int> produtoid { get; set; }
        public Nullable<System.DateTime> datareferencia { get; set; }
        public string notafiscal { get; set; }
        public Nullable<decimal> precovendaproduto { get; set; }
        public Nullable<decimal> precobaseproduto { get; set; }
        public Nullable<System.DateTime> datavenda { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string loteserie { get; set; }
        public Nullable<int> mesesgarantiafornecedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Seg_Apolices Seg_Apolices { get; set; }
    }
}
