//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicos()
        {
            this.Checklists = new HashSet<Checklists>();
            this.OportunidadesProdutosPacotesServicosServicos = new HashSet<OportunidadesProdutosPacotesServicosServicos>();
            this.OrdensServicosProdutos = new HashSet<OrdensServicosProdutos>();
            this.Servicos1 = new HashSet<Servicos>();
            this.ServicosFinalidadesOrdensServicosGerais = new HashSet<ServicosFinalidadesOrdensServicosGerais>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public decimal valor { get; set; }
        public string ativo { get; set; }
        public Nullable<int> tempoexecucao { get; set; }
        public Nullable<int> servicopaiid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklists> Checklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesProdutosPacotesServicosServicos> OportunidadesProdutosPacotesServicosServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosProdutos> OrdensServicosProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicos> Servicos1 { get; set; }
        public virtual Servicos Servicos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosFinalidadesOrdensServicosGerais> ServicosFinalidadesOrdensServicosGerais { get; set; }
    }
}
