//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicosContratosCorreios
    {
        public int id { get; set; }
        public int contratoid { get; set; }
        public int servicoid { get; set; }
    
        public virtual ContratosCorreios ContratosCorreios { get; set; }
        public virtual ServicosCorreios ServicosCorreios { get; set; }
    }
}
