//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicosAdicionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicosAdicionais()
        {
            this.FinalidadesOrdensServicosServicosAdicionaisObrigatorios = new HashSet<FinalidadesOrdensServicosServicosAdicionaisObrigatorios>();
            this.FinalidadesOrdensServicosServicosGeraisAdicionaisObrigatorios = new HashSet<FinalidadesOrdensServicosServicosGeraisAdicionaisObrigatorios>();
            this.OrdensServicosServicosAdicionais = new HashSet<OrdensServicosServicosAdicionais>();
            this.ServicosAdicionaisProdutosRestritos = new HashSet<ServicosAdicionaisProdutosRestritos>();
            this.ServicosAdicionaisTiposPostosAutorizadosRestritos = new HashSet<ServicosAdicionaisTiposPostosAutorizadosRestritos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public decimal valor { get; set; }
        public string tipo { get; set; }
        public string enviaauditoria { get; set; }
        public string ativo { get; set; }
        public string disponivelsomentefabricante { get; set; }
        public string restringesomenteumporproduto { get; set; }
        public string obrigatoriojustificativa { get; set; }
        public Nullable<decimal> valormaximo { get; set; }
        public string obrigatoriocomprovante { get; set; }
        public string enviaauditoriadivergenciacomprovante { get; set; }
        public string obrigatoriomidia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadesOrdensServicosServicosAdicionaisObrigatorios> FinalidadesOrdensServicosServicosAdicionaisObrigatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalidadesOrdensServicosServicosGeraisAdicionaisObrigatorios> FinalidadesOrdensServicosServicosGeraisAdicionaisObrigatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosServicosAdicionais> OrdensServicosServicosAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosAdicionaisProdutosRestritos> ServicosAdicionaisProdutosRestritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosAdicionaisTiposPostosAutorizadosRestritos> ServicosAdicionaisTiposPostosAutorizadosRestritos { get; set; }
    }
}
