//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOportunidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusOportunidades()
        {
            this.ChecklistsItensStatusOportunidades = new HashSet<ChecklistsItensStatusOportunidades>();
            this.MotivosPerdasOportunidadesStatusRestritos = new HashSet<MotivosPerdasOportunidadesStatusRestritos>();
            this.Oportunidades = new HashSet<Oportunidades>();
            this.OportunidadesAtualizacoesStatus = new HashSet<OportunidadesAtualizacoesStatus>();
            this.OportunidadesAtualizacoesStatus1 = new HashSet<OportunidadesAtualizacoesStatus>();
            this.OportunidadesChecklists = new HashSet<OportunidadesChecklists>();
            this.PaineisOportunidadesFluxosAtendimento = new HashSet<PaineisOportunidadesFluxosAtendimento>();
            this.PaineisOportunidadesStatusOportunidades = new HashSet<PaineisOportunidadesStatusOportunidades>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string cor { get; set; }
        public string concluiraoselecionar { get; set; }
        public string marcarcomonaoadquiridoaoselecionar { get; set; }
        public string ativo { get; set; }
        public string textoinformativo { get; set; }
        public string obrigatorioentidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistsItensStatusOportunidades> ChecklistsItensStatusOportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosPerdasOportunidadesStatusRestritos> MotivosPerdasOportunidadesStatusRestritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oportunidades> Oportunidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesAtualizacoesStatus> OportunidadesAtualizacoesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesAtualizacoesStatus> OportunidadesAtualizacoesStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesChecklists> OportunidadesChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesFluxosAtendimento> PaineisOportunidadesFluxosAtendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisOportunidadesStatusOportunidades> PaineisOportunidadesStatusOportunidades { get; set; }
    }
}
