//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOrdensServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusOrdensServicos()
        {
            this.OrdensServicos = new HashSet<OrdensServicos>();
            this.PaineisAtendimentosStatusOrdensServicos = new HashSet<PaineisAtendimentosStatusOrdensServicos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string cor { get; set; }
        public string enviaauditoria { get; set; }
        public string ativo { get; set; }
        public string statuspadraoauditoria { get; set; }
        public string concluiraoselecionar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicos> OrdensServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisAtendimentosStatusOrdensServicos> PaineisAtendimentosStatusOrdensServicos { get; set; }
    }
}
