//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusAtendimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusAtendimentos()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.AtendimentosInteracoes = new HashSet<AtendimentosInteracoes>();
            this.GruposCallCenter = new HashSet<GruposCallCenter>();
            this.PaineisAtendimentosStatusAtendimentos = new HashSet<PaineisAtendimentosStatusAtendimentos>();
            this.StatusAtendimentos1 = new HashSet<StatusAtendimentos>();
            this.StatusAtendimentos11 = new HashSet<StatusAtendimentos>();
            this.TiposOcorrencias = new HashSet<TiposOcorrencias>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string cor { get; set; }
        public Nullable<int> diasfechamentoautomatico { get; set; }
        public string ativo { get; set; }
        public string statuspadraoaposretorno { get; set; }
        public Nullable<int> prazoretornointerno { get; set; }
        public string mostrarnaconsultaweb { get; set; }
        public Nullable<int> statusatendimentoidpadraoaposretorno { get; set; }
        public Nullable<int> statusatendimentoidproximo { get; set; }
        public string mensagemfechamentoautomatico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosInteracoes> AtendimentosInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposCallCenter> GruposCallCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaineisAtendimentosStatusAtendimentos> PaineisAtendimentosStatusAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusAtendimentos> StatusAtendimentos1 { get; set; }
        public virtual StatusAtendimentos StatusAtendimentos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusAtendimentos> StatusAtendimentos11 { get; set; }
        public virtual StatusAtendimentos StatusAtendimentos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposOcorrencias> TiposOcorrencias { get; set; }
    }
}
