//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelasPrecos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabelasPrecos()
        {
            this.Carrinho = new HashSet<Carrinho>();
            this.CondicoesPagamento = new HashSet<CondicoesPagamento>();
            this.EntidadesTabelasPrecosVenda = new HashSet<EntidadesTabelasPrecosVenda>();
            this.Pedidos = new HashSet<Pedidos>();
            this.PostosAutorizados = new HashSet<PostosAutorizados>();
            this.PostosAutorizados1 = new HashSet<PostosAutorizados>();
            this.PostosAutorizadosTabelasPrecosVenda = new HashSet<PostosAutorizadosTabelasPrecosVenda>();
            this.TabelasPrecosPecas = new HashSet<TabelasPrecosPecas>();
            this.TabelasPrecosProdutos = new HashSet<TabelasPrecosProdutos>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string garantia { get; set; }
        public string consumidor { get; set; }
        public string ativo { get; set; }
        public string venda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicoesPagamento> CondicoesPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesTabelasPrecosVenda> EntidadesTabelasPrecosVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizados> PostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizados> PostosAutorizados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizadosTabelasPrecosVenda> PostosAutorizadosTabelasPrecosVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelasPrecosPecas> TabelasPrecosPecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelasPrecosProdutos> TabelasPrecosProdutos { get; set; }
    }
}
