//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelasFretes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabelasFretes()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public int cepinicial { get; set; }
        public int cepfinal { get; set; }
        public string cidadesatendidas { get; set; }
        public decimal pesoinicial { get; set; }
        public decimal pesofinal { get; set; }
        public Nullable<decimal> valorkg { get; set; }
        public Nullable<decimal> valorfixo { get; set; }
        public Nullable<int> prazoentregadias { get; set; }
        public string transportador { get; set; }
        public string linkrastreio { get; set; }
        public string codigoerptransportador { get; set; }
        public string ativo { get; set; }
        public Nullable<decimal> percentual { get; set; }
        public Nullable<int> transportadoraid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
    }
}
