//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelasPrecosPecas
    {
        public int id { get; set; }
        public int tabelaprecoid { get; set; }
        public int pecaid { get; set; }
        public decimal preco { get; set; }
    
        public virtual Pecas Pecas { get; set; }
        public virtual TabelasPrecos TabelasPrecos { get; set; }
    }
}
