//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsMessagingCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TagsMessagingCenter()
        {
            this.AtendimentosTags = new HashSet<AtendimentosTags>();
            this.ChatsTags = new HashSet<ChatsTags>();
            this.ContatosTags = new HashSet<ContatosTags>();
            this.EntidadesTags = new HashSet<EntidadesTags>();
            this.ExtratosLotesTags = new HashSet<ExtratosLotesTags>();
            this.OportunidadesTags = new HashSet<OportunidadesTags>();
            this.OrdensServicosTags = new HashSet<OrdensServicosTags>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string corfundo { get; set; }
        public string ativo { get; set; }
        public string cortexto { get; set; }
        public string habilitadomessagingcenter { get; set; }
        public string habilitadoatendimentos { get; set; }
        public string habilitadoordensservicos { get; set; }
        public string habilitadofinanceiro { get; set; }
        public string visivelpostoautorizadofinanceiro { get; set; }
        public string habilitadonegocios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentosTags> AtendimentosTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsTags> ChatsTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContatosTags> ContatosTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadesTags> EntidadesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtratosLotesTags> ExtratosLotesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunidadesTags> OportunidadesTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosTags> OrdensServicosTags { get; set; }
    }
}
