//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesMetaBotoes
    {
        public int id { get; set; }
        public int templatemetaid { get; set; }
        public string tipo { get; set; }
        public string textobotao { get; set; }
        public string url { get; set; }
    
        public virtual TemplatesMeta TemplatesMeta { get; set; }
    }
}
