//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesMeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplatesMeta()
        {
            this.AgendamentosEnviosTemplates = new HashSet<AgendamentosEnviosTemplates>();
            this.Campanhas = new HashSet<Campanhas>();
            this.ChatbotsIntencoes = new HashSet<ChatbotsIntencoes>();
            this.ChatsMensagens = new HashSet<ChatsMensagens>();
            this.TemplatesMetaBotoes = new HashSet<TemplatesMetaBotoes>();
            this.TemplatesMetaFavoritos = new HashSet<TemplatesMetaFavoritos>();
            this.TemplatesMetaVariaveis = new HashSet<TemplatesMetaVariaveis>();
        }
    
        public int id { get; set; }
        public int chatcanalid { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public string category { get; set; }
        public string language { get; set; }
        public string @namespace { get; set; }
        public string rejected_reason { get; set; }
        public string status { get; set; }
        public string interno { get; set; }
        public string ativo { get; set; }
        public string header_image_url { get; set; }
        public string useheader { get; set; }
        public string headerformat { get; set; }
        public string headermediaid { get; set; }
        public string headerimageurl { get; set; }
        public string metaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentosEnviosTemplates> AgendamentosEnviosTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campanhas> Campanhas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotsIntencoes> ChatbotsIntencoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensagens> ChatsMensagens { get; set; }
        public virtual NumerosWhatsApp NumerosWhatsApp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesMetaBotoes> TemplatesMetaBotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesMetaFavoritos> TemplatesMetaFavoritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesMetaVariaveis> TemplatesMetaVariaveis { get; set; }
    }
}
