//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesMetaVariaveis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplatesMetaVariaveis()
        {
            this.AgendamentosEnviosVariaveisTemplates = new HashSet<AgendamentosEnviosVariaveisTemplates>();
        }
    
        public int id { get; set; }
        public int templatemetaid { get; set; }
        public int variavel { get; set; }
        public string valor { get; set; }
        public string tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentosEnviosVariaveisTemplates> AgendamentosEnviosVariaveisTemplates { get; set; }
        public virtual TemplatesMeta TemplatesMeta { get; set; }
    }
}
