//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposEntidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposEntidades()
        {
            this.Entidades = new HashSet<Entidades>();
            this.ParametrosGlobais = new HashSet<ParametrosGlobais>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string sincronizarconsumidores { get; set; }
        public string sincronizarrevendedores { get; set; }
        public string disponivelmodulonegocios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametrosGlobais> ParametrosGlobais { get; set; }
    }
}
