//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPostosAutorizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposPostosAutorizados()
        {
            this.PostosAutorizados = new HashSet<PostosAutorizados>();
            this.ServicosAdicionaisTiposPostosAutorizadosRestritos = new HashSet<ServicosAdicionaisTiposPostosAutorizadosRestritos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string postointerno { get; set; }
        public string ativo { get; set; }
        public string somentecompralojavirtual { get; set; }
        public string postointernogerarextrato { get; set; }
        public string postointernogerarpedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostosAutorizados> PostosAutorizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicosAdicionaisTiposPostosAutorizadosRestritos> ServicosAdicionaisTiposPostosAutorizadosRestritos { get; set; }
    }
}
