//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposPedidos()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string padrao { get; set; }
        public string permiteinformarvalorunitario { get; set; }
        public string ocultartabelapreco { get; set; }
        public string permitirapenasquantidadefixada { get; set; }
        public string permitecondicoesespeciais { get; set; }
        public string permitedescontocapa { get; set; }
        public Nullable<int> diasvalidadeorcamento { get; set; }
        public string sugerirpercentualcomissaorepresentante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
