//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposAtendimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposAtendimentos()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.TiposOcorrenciasTiposAtendimentosRestritos = new HashSet<TiposOcorrenciasTiposAtendimentosRestritos>();
        }
    
        public int id { get; set; }
        public string tipoatendimento { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string urlformulariocustomizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposOcorrenciasTiposAtendimentosRestritos> TiposOcorrenciasTiposAtendimentosRestritos { get; set; }
    }
}
