//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposOcorrencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposOcorrencias()
        {
            this.TiposOcorrenciasTiposAtendimentosRestritos = new HashSet<TiposOcorrenciasTiposAtendimentosRestritos>();
            this.TiposOcorrenciasUsuariosReaberturaRestritos = new HashSet<TiposOcorrenciasUsuariosReaberturaRestritos>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
        public string disponivelaplicativo { get; set; }
        public string ocultardefeitoreclamado { get; set; }
        public Nullable<int> statusatendimentoid { get; set; }
        public string padrao { get; set; }
        public string numeroserieobrigatorio { get; set; }
        public string notafiscalobrigatorio { get; set; }
        public string datacompraobrigatorio { get; set; }
        public string produtoobrigatorio { get; set; }
        public string motivoenviopecaobrigatorio { get; set; }
        public string defeitoreclamadoobrigatorio { get; set; }
        public string notificarreincidencianumeroloteserie { get; set; }
        public Nullable<int> vezesnotificarreincidencianumeroloteserie { get; set; }
        public Nullable<int> diasnotificarreincidencianumeroloteserie { get; set; }
        public string emailnotificarreincidencianumeroloteserie { get; set; }
        public string obrigatorioselecionarcontatoparceirorecebeatendimento { get; set; }
        public string obrigatoriodadosapolice { get; set; }
    
        public virtual StatusAtendimentos StatusAtendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposOcorrenciasTiposAtendimentosRestritos> TiposOcorrenciasTiposAtendimentosRestritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposOcorrenciasUsuariosReaberturaRestritos> TiposOcorrenciasUsuariosReaberturaRestritos { get; set; }
    }
}
