//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposOcorrenciasTiposAtendimentosRestritos
    {
        public int id { get; set; }
        public int tipoocorrenciaid { get; set; }
        public int tipoatendimentoid { get; set; }
    
        public virtual TiposAtendimentos TiposAtendimentos { get; set; }
        public virtual TiposOcorrencias TiposOcorrencias { get; set; }
    }
}
