//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportadoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportadoras()
        {
            this.Atendimentos = new HashSet<Atendimentos>();
            this.Entidades = new HashSet<Entidades>();
            this.Entidades1 = new HashSet<Entidades>();
            this.Pedidos = new HashSet<Pedidos>();
            this.Pedidos1 = new HashSet<Pedidos>();
            this.TabelasFretes = new HashSet<TabelasFretes>();
        }
    
        public int id { get; set; }
        public string referencia { get; set; }
        public string cpfcnpj { get; set; }
        public string nomerazaosocial { get; set; }
        public string telefone { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public string rginscricaoestadual { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string email { get; set; }
        public string char1 { get; set; }
        public string telefonepais { get; set; }
        public string telefonesiglapais { get; set; }
        public string telefonedialcodepais { get; set; }
        public string telefone2pais { get; set; }
        public string telefone2siglapais { get; set; }
        public string telefone2dialcodepais { get; set; }
        public string telefone3pais { get; set; }
        public string telefone3siglapais { get; set; }
        public string telefone3dialcodepais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimentos> Atendimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelasFretes> TabelasFretes { get; set; }
    }
}
