//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualizacaoConsultaPublicaLinks
    {
        public int id { get; set; }
        public Nullable<int> ordemid { get; set; }
        public Nullable<int> atendimentoid { get; set; }
        public string hash { get; set; }
        public System.DateTime datacriacao { get; set; }
        public System.DateTime datavalidade { get; set; }
        public int usuarioidcriacao { get; set; }
        public string usuarionomecriacao { get; set; }
        public Nullable<System.DateTime> datarevogacao { get; set; }
        public int acessos { get; set; }
        public string status { get; set; }
        public Nullable<int> pedidoid { get; set; }
    
        public virtual Atendimentos Atendimentos { get; set; }
        public virtual OrdensServicos OrdensServicos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
