//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualizacaoConsultaPublicaCampos
    {
        public int id { get; set; }
        public int consultapublicaid { get; set; }
        public string campo { get; set; }
        public string exibir { get; set; }
    
        public virtual VisualizacaoConsultaPublica VisualizacaoConsultaPublica { get; set; }
    }
}
