//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualizacaoConsultaPublica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisualizacaoConsultaPublica()
        {
            this.VisualizacaoConsultaPublicaCampos = new HashSet<VisualizacaoConsultaPublicaCampos>();
            this.VisualizacaoConsultaPublicaEstilizacao = new HashSet<VisualizacaoConsultaPublicaEstilizacao>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public Nullable<int> logoempresafileid { get; set; }
    
        public virtual Files Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualizacaoConsultaPublicaCampos> VisualizacaoConsultaPublicaCampos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisualizacaoConsultaPublicaEstilizacao> VisualizacaoConsultaPublicaEstilizacao { get; set; }
    }
}
