//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebScraperCampos
    {
        public int id { get; set; }
        public int webscraperid { get; set; }
        public string buscardentrodetalhe { get; set; }
        public string nomecampo { get; set; }
        public string tipocampo { get; set; }
        public string xpath { get; set; }
        public string atributo { get; set; }
        public string obrigatorio { get; set; }
    
        public virtual WebScraper WebScraper { get; set; }
    }
}
