//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suggar_client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebScraper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebScraper()
        {
            this.WebScraperCampos = new HashSet<WebScraperCampos>();
        }
    
        public int id { get; set; }
        public Nullable<int> chatgptid { get; set; }
        public System.DateTime datacriacao { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
        public string xpathcontainer { get; set; }
        public string xpathitem { get; set; }
        public string campolinkdetalhe { get; set; }
        public string ecom { get; set; }
        public string substituirtreinamentoanterior { get; set; }
        public string executasegunda { get; set; }
        public string executaterca { get; set; }
        public string executaquarta { get; set; }
        public string executaquinta { get; set; }
        public string executasexta { get; set; }
        public string executasabado { get; set; }
        public string executadomingo { get; set; }
        public string xpathnextpage { get; set; }
    
        public virtual ChatGPT ChatGPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebScraperCampos> WebScraperCampos { get; set; }
    }
}
